/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.wesleycoelho.view;
import com.wesleycoelho.controllers.jdbc.conn.ClienteDB;
import com.wesleycoelho.controllers.jdbc.conn.EntradaVeiculoDB;
import com.wesleycoelho.controllers.jdbc.conn.EstadoDB;
import com.wesleycoelho.controllers.jdbc.conn.FinanciamentoDB;
import com.wesleycoelho.controllers.jdbc.conn.MunicipioDB;
import com.wesleycoelho.controllers.jdbc.conn.SaidaVeiculoDB;
import com.wesleycoelho.model.Cliente;
import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Financiamento;
import com.wesleycoelho.model.Municipio;
import com.wesleycoelho.model.PrintingFichaFrenteFinanciamento;
import com.wesleycoelho.model.PrintingFichaVersoFinanciamento;
import com.wesleycoelho.model.SaidaVeiculo;
import com.wesleycoelho.model.Usuario;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import static java.lang.Integer.parseInt;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Wesley
 */
public class FormPesquisaFinanciamento extends javax.swing.JInternalFrame {
    Usuario usuario = new Usuario();
    List<Financiamento> financiamentos;
    int iteratorLista = 0;
    /**
     * Creates new form FormNovaEntrada
     */
    public FormPesquisaFinanciamento(Usuario user) {
        this.usuario = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dtFinanciamento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cbQtdParcelasFinanciamento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbDiaVencimentoFinanciamento = new javax.swing.JComboBox<>();
        txtValParcelaFinanciamento = new javax.swing.JFormattedTextField();
        txtObsFinanciamento = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSalvarEntrada = new javax.swing.JButton();
        btnImprimirEntrada = new javax.swing.JButton();
        btnExcluirEntrada = new javax.swing.JButton();
        btnLimparFormularioEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPesquisarFinanciamento = new javax.swing.JButton();
        txtPesquisarFinanciamento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbFiltroPesquisa = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        lblAtualResult = new javax.swing.JLabel();
        btnPreviousResult = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNextResult = new javax.swing.JButton();
        lblTotalLista = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtChassiEntrada = new javax.swing.JTextField();
        cbAnoEntrada = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtRenavamEntrada = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbCorEntrada = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtMarcaEntrada = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPlacaEntrada = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtModeloEntrada = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFinanciamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCEPFinanciamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnderecoFinanciamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBairroFinanciamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroFinanciamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbCidadeFinanciamento = new javax.swing.JComboBox<>();
        cbUFFinanciamento = new javax.swing.JComboBox<>();
        txtRgFinanciamento = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        txtWhatsappFinanciamento = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTelefoneFinanciamento = new javax.swing.JFormattedTextField();
        txtCPFFinanciamento = new javax.swing.JTextField();
        txtComplementoFinanciamento = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PESQUISA de financiamentos");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-car-16_1.png"))); // NOI18N
        setVisible(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(243, 245, 251));

        jLabel10.setText("*DATA:");

        dtFinanciamento.setDateFormatString("dd'-'MM'-'yyyy");
        dtFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dtFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel11.setText("*QTD. PARCELAS:");

        cbQtdParcelasFinanciamento.setEditable(true);
        cbQtdParcelasFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "6", "10", "12", "18", "24", "30", "36", "42", "48", "50", "60", "72", " " }));

        jLabel12.setText("*VALOR PARCELA:");

        jLabel15.setText("*DIA DE VENCIMENTO: ");

        cbDiaVencimentoFinanciamento.setEditable(true);
        cbDiaVencimentoFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20", "25" }));

        txtValParcelaFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValParcelaFinanciamento.setText("0,00");
        txtValParcelaFinanciamento.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValParcelaFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValParcelaFinanciamentoKeyPressed(evt);
            }
        });

        txtObsFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObsFinanciamentoKeyPressed(evt);
            }
        });

        jLabel27.setText("OBS:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtObsFinanciamento))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dtFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbDiaVencimentoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbDiaVencimentoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtObsFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSalvarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-16.png"))); // NOI18N
        btnSalvarEntrada.setToolTipText("Salvar");
        btnSalvarEntrada.setEnabled(false);
        btnSalvarEntrada.setFocusable(false);
        btnSalvarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvarEntrada);

        btnImprimirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-print-16.png"))); // NOI18N
        btnImprimirEntrada.setToolTipText("Imprimir");
        btnImprimirEntrada.setFocusable(false);
        btnImprimirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirEntrada);

        btnExcluirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-trash-16.png"))); // NOI18N
        btnExcluirEntrada.setToolTipText("Excluir");
        btnExcluirEntrada.setEnabled(false);
        btnExcluirEntrada.setFocusable(false);
        btnExcluirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirEntrada);

        btnLimparFormularioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-broom-16.png"))); // NOI18N
        btnLimparFormularioEntrada.setToolTipText("Limpar Formulário");
        btnLimparFormularioEntrada.setEnabled(false);
        btnLimparFormularioEntrada.setFocusable(false);
        btnLimparFormularioEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFormularioEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFormularioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparFormularioEntradaMouseClicked(evt);
            }
        });
        btnLimparFormularioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormularioEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimparFormularioEntrada);
        jToolBar1.add(jSeparator1);

        btnPesquisarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-16.png"))); // NOI18N
        btnPesquisarFinanciamento.setFocusable(false);
        btnPesquisarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarFinanciamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFinanciamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPesquisarFinanciamento);

        txtPesquisarFinanciamento.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisarFinanciamento.setMaximumSize(new java.awt.Dimension(300, 22));
        txtPesquisarFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarFinanciamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPesquisarFinanciamentoMouseEntered(evt);
            }
        });
        txtPesquisarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarFinanciamentoActionPerformed(evt);
            }
        });
        txtPesquisarFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarFinanciamentoKeyReleased(evt);
            }
        });
        jToolBar1.add(txtPesquisarFinanciamento);

        jLabel17.setText("     ");
        jToolBar1.add(jLabel17);

        cbFiltroPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data", "Nome do cliente", "Observação", "Id", "Dia do vencimento", " " }));
        cbFiltroPesquisa.setMaximumSize(new java.awt.Dimension(300, 22));
        cbFiltroPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFiltroPesquisaItemStateChanged(evt);
            }
        });
        cbFiltroPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbFiltroPesquisaFocusGained(evt);
            }
        });
        cbFiltroPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroPesquisaActionPerformed(evt);
            }
        });
        jToolBar1.add(cbFiltroPesquisa);
        jToolBar1.add(jSeparator2);

        lblAtualResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtualResult.setText("0");
        lblAtualResult.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblAtualResult.setIconTextGap(20);
        lblAtualResult.setMaximumSize(new java.awt.Dimension(30, 16));
        lblAtualResult.setMinimumSize(new java.awt.Dimension(10, 16));
        lblAtualResult.setPreferredSize(new java.awt.Dimension(20, 16));
        jToolBar1.add(lblAtualResult);

        btnPreviousResult.setText("<");
        btnPreviousResult.setFocusable(false);
        btnPreviousResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPreviousResult.setMaximumSize(new java.awt.Dimension(30, 24));
        btnPreviousResult.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPreviousResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousResultActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPreviousResult);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("de");
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 16));
        jToolBar1.add(jLabel2);

        btnNextResult.setText(">");
        btnNextResult.setFocusable(false);
        btnNextResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNextResult.setMaximumSize(new java.awt.Dimension(30, 24));
        btnNextResult.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNextResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextResultActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNextResult);

        lblTotalLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalLista.setText("0");
        lblTotalLista.setMaximumSize(new java.awt.Dimension(30, 16));
        lblTotalLista.setMinimumSize(new java.awt.Dimension(10, 16));
        jToolBar1.add(lblTotalLista);

        jPanel1.setBackground(new java.awt.Color(243, 245, 251));

        cbAnoEntrada.setEditable(true);
        cbAnoEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbAnoEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel22.setText("ANO:");

        jLabel21.setText("PLACA:");

        cbCorEntrada.setEditable(true);
        cbCorEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDE", "AMARELO", "PRETO", "CINZA", "AZUL", "BRANCO", "CHUMBO", "PRATA", "VINHO", "BEGE", "VERMELHO", " " }));
        cbCorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyTyped(evt);
            }
        });

        jLabel19.setText("RENAVAM:");

        jLabel16.setText("MARCA:");

        jLabel20.setText("CHASSI:");

        jLabel23.setText("COR:");

        jLabel18.setText("MODELO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChassiEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenavamEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModeloEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarcaEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMarcaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtRenavamEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChassiEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(243, 245, 251));

        jLabel1.setText("*NOME:");

        txtNomeFinanciamento.setActionCommand("null");
        txtNomeFinanciamento.setVerifyInputWhenFocusTarget(false);
        txtNomeFinanciamento.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeFinanciamentoCaretUpdate(evt);
            }
        });
        txtNomeFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFinanciamentoFocusGained(evt);
            }
        });
        txtNomeFinanciamento.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtNomeFinanciamentoComponentMoved(evt);
            }
        });
        txtNomeFinanciamento.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                none(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNomeFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyTyped(evt);
            }
        });

        jLabel3.setText("RG:");

        jLabel24.setText("CPF:");

        jLabel4.setText("CEP:");

        txtCEPFinanciamento.setPreferredSize(new java.awt.Dimension(90, 22));
        txtCEPFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPFinanciamentoActionPerformed(evt);
            }
        });
        txtCEPFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCEPFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCEPFinanciamentoKeyReleased(evt);
            }
        });

        jLabel5.setText("*ENDEREÇO:");

        txtEnderecoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoFinanciamentoKeyReleased(evt);
            }
        });

        jLabel6.setText("*BAIRRO:");

        txtBairroFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroFinanciamentoKeyReleased(evt);
            }
        });

        jLabel7.setText("*NÚMERO:");

        txtNumeroFinanciamento.setPreferredSize(new java.awt.Dimension(77, 22));
        txtNumeroFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroFinanciamentoKeyReleased(evt);
            }
        });

        jLabel8.setText("MUNICÍPIO:");

        jLabel9.setText("UF:");

        cbCidadeFinanciamento.setEditable(true);
        cbCidadeFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ribeirao Preto" }));
        cbCidadeFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCidadeFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbUFFinanciamento.setEditable(true);
        cbUFFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo" }));
        cbUFFinanciamento.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbUFFinanciamentoComponentAdded(evt);
            }
        });
        cbUFFinanciamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFFinanciamentoItemStateChanged(evt);
            }
        });
        cbUFFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbUFFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        try {
            txtRgFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRgFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRgFinanciamentoKeyPressed(evt);
            }
        });

        jLabel25.setText("*Telefone:");

        try {
            txtWhatsappFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtWhatsappFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWhatsappFinanciamentoKeyPressed(evt);
            }
        });

        jLabel26.setText("Whatsapp:");

        try {
            txtTelefoneFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneFinanciamentoKeyPressed(evt);
            }
        });

        txtCPFFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFinanciamentoFocusLost(evt);
            }
        });
        txtCPFFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFFinanciamentoKeyPressed(evt);
            }
        });

        txtComplementoFinanciamento.setPreferredSize(new java.awt.Dimension(90, 22));
        txtComplementoFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoFinanciamentoActionPerformed(evt);
            }
        });
        txtComplementoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComplementoFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoFinanciamentoKeyReleased(evt);
            }
        });

        jLabel28.setText("COMPL:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeFinanciamento)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(txtCEPFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnderecoFinanciamento)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBairroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtComplementoFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txtWhatsappFinanciamento))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbCidadeFinanciamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbUFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel24)
                    .addComponent(jLabel4)
                    .addComponent(txtCEPFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(txtComplementoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBairroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbCidadeFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtWhatsappFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEntradaActionPerformed
        // TODO add your handling code here: 
        
        
        
        
        
        
    }//GEN-LAST:event_btnSalvarEntradaActionPerformed

    private void btnImprimirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEntradaActionPerformed
        try{
            if(financiamentos.get(iteratorLista) == null) throw new NullPointerException("Nenhum financiamento para imprimir");
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(new PrintingFichaFrenteFinanciamento(financiamentos.get(iteratorLista)));
            boolean doPrint = job.printDialog();
                if (doPrint) job.print();            
        }catch (PrinterException | NullPointerException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() );
            }
        int imprimirFichaVerso = JOptionPane.showConfirmDialog(rootPane, "Deja impirmir o verso da ficha?");
                if( imprimirFichaVerso == 0  ){
                    PrinterJob job = PrinterJob.getPrinterJob();
                    job.setPrintable(new PrintingFichaVersoFinanciamento(financiamentos.get(iteratorLista)));
                    boolean doPrint = job.printDialog();
                        if (doPrint) try {
                            job.print();
                    } catch (PrinterException ex) {
                        Logger.getLogger(FormNovoFinanciamento.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                   
    }//GEN-LAST:event_btnImprimirEntradaActionPerformed

    private void btnExcluirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEntradaActionPerformed

    private void btnLimparFormularioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparFormularioEntradaActionPerformed

    private void txtPesquisarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoActionPerformed
        // TODO add your handling code here:
        this.txtPesquisarFinanciamento.setText(this.txtPesquisarFinanciamento.getText().toUpperCase());
    }//GEN-LAST:event_txtPesquisarFinanciamentoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:        
        Financiamento.janelaPesquisaFinanciamento = true;
        System.out.println(Financiamento.janelaPesquisaFinanciamento);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtPesquisarFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoMouseClicked
        //recuperando os dados do formulario
        this.txtPesquisarFinanciamento.setText("");
    }//GEN-LAST:event_txtPesquisarFinanciamentoMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        Financiamento.janelaPesquisaFinanciamento = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        Financiamento.janelaPesquisaFinanciamento = true;
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
        Financiamento.janelaPesquisaFinanciamento = false;
    }//GEN-LAST:event_formAncestorRemoved

    private void btnLimparFormularioEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaMouseClicked
        // TODO add your handling code here:
        this.txtChassiEntrada.setText("");
        this.txtMarcaEntrada.setText("");
        this.txtModeloEntrada.setText("");
        this.txtPlacaEntrada.setText("");
        this.txtRenavamEntrada.setText("");
    }//GEN-LAST:event_btnLimparFormularioEntradaMouseClicked

    private void txtPesquisarFinanciamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesquisarFinanciamentoMouseEntered

    private void btnPesquisarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoActionPerformed
        // TODO add your handling code here:
        if( !this.txtPesquisarFinanciamento.getText().isBlank() ){
            if( this.cbFiltroPesquisa.getSelectedItem().toString() == "Data"){
                //buscar financiamentos por data
                financiamentos = FinanciamentoDB.buscaPorData(this.txtPesquisarFinanciamento.getText());
                if( financiamentos != null && financiamentos.size() > 0){
                   
                    this.lblTotalLista.setText(String.valueOf(financiamentos.size()));
                    atualizaListaFinanciamento(this.iteratorLista);
                    
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!");
                    return;
                }
            }else if( this.cbFiltroPesquisa.getSelectedItem().toString() == "Nome do cliente" ){
               //buscar pelo nome do cliente 
               financiamentos = FinanciamentoDB.buscaPorNome(this.txtPesquisarFinanciamento.getText());
                if( financiamentos != null && financiamentos.size() > 0){
                     this.lblTotalLista.setText(String.valueOf(financiamentos.size()));
                    atualizaListaFinanciamento(this.iteratorLista);                    
                }else{
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!");
                      return;
                }
               
            }else if( this.cbFiltroPesquisa.getSelectedItem().toString() == "Observação" ){
               //buscar pelo que esta no campo observacao
               financiamentos = FinanciamentoDB.buscaPorObs(this.txtPesquisarFinanciamento.getText());
                if( financiamentos != null && financiamentos.size() > 0){
                     this.lblTotalLista.setText(String.valueOf(financiamentos.size()));
                    atualizaListaFinanciamento(this.iteratorLista);                    
                }else{
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!");
                      return;
                }
            }else if( this.cbFiltroPesquisa.getSelectedItem().toString() == "id" ){
               //buscar pelo id              
                if( FinanciamentoDB.buscaPorId(parseInt(this.txtPesquisarFinanciamento.getText())) != null){
                     this.lblTotalLista.setText("1");
                    atualizaListaFinanciamento(this.iteratorLista);                    
                }else{
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!");
                      return;
                }
            }else if( this.cbFiltroPesquisa.getSelectedItem().toString() == "Dia do vencimento" ){
               //buscar pelo dia_vencimento 
               financiamentos = FinanciamentoDB.buscaPorDiaVencimento(parseInt(this.txtPesquisarFinanciamento.getText()));
                if( financiamentos != null && financiamentos.size() > 0){
                     this.lblTotalLista.setText(String.valueOf(financiamentos.size()));
                    atualizaListaFinanciamento(this.iteratorLista);                    
                }else{
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!");
                      return;
                }
            }
        }
        
    }//GEN-LAST:event_btnPesquisarFinanciamentoActionPerformed

    private void cbFiltroPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFiltroPesquisaFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbFiltroPesquisaFocusGained

    private void cbFiltroPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFiltroPesquisaActionPerformed

    private void btnNextResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextResultActionPerformed
        // TODO add your handling code here:
        if(iteratorLista+1 < this.financiamentos.size()){
            this.iteratorLista+=1;
            atualizaListaFinanciamento(this.iteratorLista);         
        }
       
    }//GEN-LAST:event_btnNextResultActionPerformed

    private void btnPreviousResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousResultActionPerformed
        // TODO add your handling code here:
        if(iteratorLista-1 > -1){
            this.iteratorLista-=1;
            atualizaListaFinanciamento(this.iteratorLista);             
        }
    }//GEN-LAST:event_btnPreviousResultActionPerformed

    private void txtNomeFinanciamentoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoCaretUpdate

    private void txtNomeFinanciamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoFocusGained

    private void txtNomeFinanciamentoComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoComponentMoved

    private void none(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void txtNomeFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtNomeFinanciamentoKeyPressed

    private void txtNomeFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtNomeFinanciamentoKeyReleased

    private void txtNomeFinanciamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoKeyTyped

    private void txtCEPFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPFinanciamentoActionPerformed

    private void txtCEPFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoKeyPressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_txtCEPFinanciamentoKeyPressed

    private void txtCEPFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCEPFinanciamentoKeyReleased

    private void txtEnderecoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoFinanciamentoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtEnderecoFinanciamentoKeyPressed

    private void txtEnderecoFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoFinanciamentoKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtEnderecoFinanciamentoKeyReleased

    private void txtBairroFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBairroFinanciamentoKeyPressed

    private void txtBairroFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroFinanciamentoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBairroFinanciamentoKeyReleased

    private void txtNumeroFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFinanciamentoKeyReleased
        // TODO add your handling code here:

       
    }//GEN-LAST:event_txtNumeroFinanciamentoKeyReleased

    private void cbCidadeFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCidadeFinanciamentoAncestorAdded
        // TODO add your handling code here:
   
    }//GEN-LAST:event_cbCidadeFinanciamentoAncestorAdded

    private void cbUFFinanciamentoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbUFFinanciamentoComponentAdded

    private void cbUFFinanciamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbUFFinanciamentoItemStateChanged

    private void cbUFFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbUFFinanciamentoAncestorAdded

    private void txtRgFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRgFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRgFinanciamentoKeyPressed

    private void txtWhatsappFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhatsappFinanciamentoKeyPressed
       
    }//GEN-LAST:event_txtWhatsappFinanciamentoKeyPressed

    private void txtTelefoneFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFinanciamentoKeyPressed
     
    }//GEN-LAST:event_txtTelefoneFinanciamentoKeyPressed

    private void txtCPFFinanciamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoFocusLost
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtCPFFinanciamentoFocusLost

    private void txtCPFFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCPFFinanciamentoKeyPressed

    private void dtFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dtFinanciamentoAncestorAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_dtFinanciamentoAncestorAdded

    private void txtValParcelaFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValParcelaFinanciamentoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtValParcelaFinanciamentoKeyPressed

    private void txtObsFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsFinanciamentoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtObsFinanciamentoKeyPressed

    private void cbFiltroPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFiltroPesquisaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFiltroPesquisaItemStateChanged

    private void txtPesquisarFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtPesquisarFinanciamento.setText(this.txtPesquisarFinanciamento.getText().toUpperCase());
    }//GEN-LAST:event_txtPesquisarFinanciamentoKeyReleased

    private void txtComplementoFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoFinanciamentoActionPerformed

    private void txtComplementoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoFinanciamentoKeyPressed

    private void txtComplementoFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtComplementoFinanciamento.setText(this.txtComplementoFinanciamento.getText().toUpperCase());
    }//GEN-LAST:event_txtComplementoFinanciamentoKeyReleased

    private void cbCorEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCorEntradaKeyTyped

    private void cbAnoEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbAnoEntradaAncestorAdded
        // TODO add your handling code here:
        for (int i = 1950; i < 2061; i++) {
            this.cbAnoEntrada.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_cbAnoEntradaAncestorAdded

    
    private void atualizaListaFinanciamento(int iterator){
        int id_cliente;
        Municipio municipio;
        String estado;
        //obtendo o cliente
        Cliente cliente ;
        cliente = ClienteDB.buscaClientePorId(financiamentos.get(iterator).getId_cliente());
        if(cliente != null){
            this.txtNomeFinanciamento.setText(cliente.getNome());
            this.txtRgFinanciamento.setText(cliente.getRg());
            this.txtCPFFinanciamento.setText(cliente.getCpf());
            this.txtCEPFinanciamento.setText(cliente.getCep());
            this.txtEnderecoFinanciamento.setText(cliente.getEndereco());
            this.txtBairroFinanciamento.setText(cliente.getBairro());
            this.txtNumeroFinanciamento.setText(String.valueOf(cliente.getNumero()));
            municipio = MunicipioDB.buscaCidadePorId(cliente.getId_municipio());
            if(municipio != null){
                this.cbCidadeFinanciamento.setSelectedItem(municipio.getNome());
            }else{
                JOptionPane.showMessageDialog(this, "id_municipio não encontrado na tabela municipio");
            }
            estado = EstadoDB.searchById(municipio.getId_uf()).getNome();
            if(estado != null){
                this.cbUFFinanciamento.setSelectedItem(estado);
            }else{
                JOptionPane.showMessageDialog(this, "id_uf não encontrado na tabela estado");
            }
            this.txtWhatsappFinanciamento.setText(cliente.getWhatsapp());
            this.txtTelefoneFinanciamento.setText(cliente.getTelefone());
            this.txtComplementoFinanciamento.setText(cliente.getComplemento());
            
        }else{
            JOptionPane.showMessageDialog(this, "Cliente não encontrado");
            return;
        }
        //fim cliente
        
        //obtendo a saida veiculo
        SaidaVeiculo saida = null;
        saida = SaidaVeiculoDB.buscaSaidaPorIdFinanciamento(financiamentos.get(iterator).getId());
        if(saida != null){
            //obtendo entrada pelo id_entrada
            EntradaVeiculo entrada = null;
            entrada = EntradaVeiculoDB.buscaEntradaPorId(saida.getId_entrada());
            if(entrada != null){
                this.txtMarcaEntrada.setText(entrada.getMarca());
                this.txtModeloEntrada.setText(entrada.getModelo());
                this.txtRenavamEntrada.setText(entrada.getRenavam());
                this.txtChassiEntrada.setText(entrada.getChassi());
                this.txtPlacaEntrada.setText(entrada.getPlaca());
                this.cbAnoEntrada.setSelectedItem(entrada.getAno());
                this.cbCorEntrada.setSelectedItem(entrada.getCor());
                
                //preenchendo os dados do financiamento
                this.dtFinanciamento.setDate(financiamentos.get(iterator).getData_registro());
                this.txtValParcelaFinanciamento.setText(String.valueOf(financiamentos.get(iterator).getValor_parcela()));                
                this.cbQtdParcelasFinanciamento.setSelectedItem(String.valueOf(financiamentos.get(iterator).getNum_parcelas()));
                this.cbDiaVencimentoFinanciamento.setSelectedItem(String.valueOf(financiamentos.get(iterator).getDia_vencimento()));
                this.txtObsFinanciamento.setText(financiamentos.get(iterator).getOberservacao());
                this.lblAtualResult.setText(String.valueOf(iterator + 1));
            }else{
                JOptionPane.showMessageDialog(this, "Entrada veículo não localizada");
                return;
            }//fim entrada
        }else{
            JOptionPane.showMessageDialog(this, "Saida não localizada");
            return;
        }//fim saida
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirEntrada;
    private javax.swing.JButton btnImprimirEntrada;
    private javax.swing.JButton btnLimparFormularioEntrada;
    private javax.swing.JButton btnNextResult;
    private javax.swing.JButton btnPesquisarFinanciamento;
    private javax.swing.JButton btnPreviousResult;
    private javax.swing.JButton btnSalvarEntrada;
    private javax.swing.JComboBox<String> cbAnoEntrada;
    private javax.swing.JComboBox<String> cbCidadeFinanciamento;
    private javax.swing.JComboBox<String> cbCorEntrada;
    private javax.swing.JComboBox<String> cbDiaVencimentoFinanciamento;
    private javax.swing.JComboBox<String> cbFiltroPesquisa;
    private javax.swing.JComboBox<String> cbQtdParcelasFinanciamento;
    private javax.swing.JComboBox<String> cbUFFinanciamento;
    private com.toedter.calendar.JDateChooser dtFinanciamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAtualResult;
    private javax.swing.JLabel lblTotalLista;
    private javax.swing.JTextField txtBairroFinanciamento;
    private javax.swing.JTextField txtCEPFinanciamento;
    private javax.swing.JTextField txtCPFFinanciamento;
    private javax.swing.JTextField txtChassiEntrada;
    private javax.swing.JTextField txtComplementoFinanciamento;
    private javax.swing.JTextField txtEnderecoFinanciamento;
    private javax.swing.JTextField txtMarcaEntrada;
    private javax.swing.JTextField txtModeloEntrada;
    private javax.swing.JTextField txtNomeFinanciamento;
    private javax.swing.JTextField txtNumeroFinanciamento;
    private javax.swing.JTextField txtObsFinanciamento;
    private javax.swing.JTextField txtPesquisarFinanciamento;
    private javax.swing.JTextField txtPlacaEntrada;
    private javax.swing.JTextField txtRenavamEntrada;
    private javax.swing.JFormattedTextField txtRgFinanciamento;
    private javax.swing.JFormattedTextField txtTelefoneFinanciamento;
    private javax.swing.JFormattedTextField txtValParcelaFinanciamento;
    private javax.swing.JFormattedTextField txtWhatsappFinanciamento;
    // End of variables declaration//GEN-END:variables
}
