/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.wesleycoelho.view;
import com.wesleycoelho.controllers.jdbc.conn.ClienteDB;
import com.wesleycoelho.controllers.jdbc.conn.EntradaVeiculoDB;
import com.wesleycoelho.controllers.jdbc.conn.EstadoDB;
import com.wesleycoelho.controllers.jdbc.conn.FinanciamentoDB;
import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Usuario;
import javax.swing.JOptionPane;
import com.wesleycoelho.controllers.jdbc.conn.MunicipioDB;
import com.wesleycoelho.controllers.jdbc.conn.ParcelamentoDB;
import com.wesleycoelho.controllers.jdbc.conn.SaidaVeiculoDB;
import com.wesleycoelho.model.Cliente;
import com.wesleycoelho.model.Estado;
import com.wesleycoelho.model.Financiamento;
import com.wesleycoelho.model.Municipio;
import com.wesleycoelho.model.Parcelamento;
import com.wesleycoelho.model.PrintingFichaFrenteFinanciamento;
import com.wesleycoelho.model.PrintingFichaVersoFinanciamento;
import com.wesleycoelho.model.SaidaVeiculo;
import com.wesleycoelho.model.Validacao;
import java.awt.Component;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;




/**
 *
 * @author Wesley
 */
public class FormNovoFinanciamento extends javax.swing.JInternalFrame {
    Usuario usuario = new Usuario();
    EntradaVeiculo entrada;
    /**
     * Creates new form FormNovaEntrada
     */
    public FormNovoFinanciamento(Usuario user) {
        this.usuario = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSalvarFinanciamento = new javax.swing.JButton();
        btnImprimirEntrada = new javax.swing.JButton();
        btnExcluirEntrada = new javax.swing.JButton();
        btnLimparFormularioEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel22 = new javax.swing.JLabel();
        txtPesquisarPlaca = new javax.swing.JTextField();
        btnPesquisarEntrada = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFinanciamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCEPFinanciamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnderecoFinanciamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBairroFinanciamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroFinanciamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbCidadeFinanciamento = new javax.swing.JComboBox<>();
        cbUFFinanciamento = new javax.swing.JComboBox<>();
        txtRgFinanciamento = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        txtWhatsappFinanciamento = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTelefoneFinanciamento = new javax.swing.JFormattedTextField();
        txtCPFFinanciamento = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtComplementoFinanciamento = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dtFinanciamento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cbQtdParcelasFinanciamento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbDiaVencimentoFinanciamento = new javax.swing.JComboBox<>();
        txtValVeiculoFinanciamento = new javax.swing.JFormattedTextField();
        txtValParcelaFinanciamento = new javax.swing.JFormattedTextField();
        txtValEntradafinanciamento = new javax.swing.JFormattedTextField();
        txtObsFinanciamento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtFicha = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtModeloEntrada = new javax.swing.JTextField();
        txtMarcaEntrada = new javax.swing.JTextField();
        txtRenavamEntrada = new javax.swing.JTextField();
        txtChassiEntrada = new javax.swing.JTextField();
        txtPlacaEntrada = new javax.swing.JTextField();
        cbAnoEntrada = new javax.swing.JComboBox<>();
        cbCorEntrada = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("NOVO financiamento");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-car-16_1.png"))); // NOI18N
        setVisible(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSalvarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-16.png"))); // NOI18N
        btnSalvarFinanciamento.setToolTipText("Salvar");
        btnSalvarFinanciamento.setFocusable(false);
        btnSalvarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarFinanciamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFinanciamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvarFinanciamento);

        btnImprimirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-print-16.png"))); // NOI18N
        btnImprimirEntrada.setToolTipText("Imprimir");
        btnImprimirEntrada.setEnabled(false);
        btnImprimirEntrada.setFocusable(false);
        btnImprimirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirEntrada);

        btnExcluirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-trash-16.png"))); // NOI18N
        btnExcluirEntrada.setToolTipText("Excluir");
        btnExcluirEntrada.setEnabled(false);
        btnExcluirEntrada.setFocusable(false);
        btnExcluirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirEntrada);

        btnLimparFormularioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-broom-16.png"))); // NOI18N
        btnLimparFormularioEntrada.setToolTipText("Limpar Formulário");
        btnLimparFormularioEntrada.setFocusable(false);
        btnLimparFormularioEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFormularioEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFormularioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparFormularioEntradaMouseClicked(evt);
            }
        });
        btnLimparFormularioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormularioEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimparFormularioEntrada);
        jToolBar1.add(jSeparator1);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("PLACA:");
        jLabel22.setMaximumSize(new java.awt.Dimension(60, 16));
        jLabel22.setMinimumSize(new java.awt.Dimension(60, 16));
        jToolBar1.add(jLabel22);

        txtPesquisarPlaca.setToolTipText("Digite a placa");
        txtPesquisarPlaca.setDoubleBuffered(true);
        txtPesquisarPlaca.setMaximumSize(new java.awt.Dimension(200, 20));
        txtPesquisarPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarPlacaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPesquisarPlacaMouseReleased(evt);
            }
        });
        txtPesquisarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarPlacaActionPerformed(evt);
            }
        });
        txtPesquisarPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarPlacaKeyReleased(evt);
            }
        });
        jToolBar1.add(txtPesquisarPlaca);

        btnPesquisarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-16.png"))); // NOI18N
        btnPesquisarEntrada.setFocusable(false);
        btnPesquisarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPesquisarEntrada);

        jPanel5.setBackground(new java.awt.Color(243, 245, 251));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel1.setText("*NOME:");

        txtNomeFinanciamento.setActionCommand("null");
        txtNomeFinanciamento.setVerifyInputWhenFocusTarget(false);
        txtNomeFinanciamento.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeFinanciamentoCaretUpdate(evt);
            }
        });
        txtNomeFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFinanciamentoFocusGained(evt);
            }
        });
        txtNomeFinanciamento.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtNomeFinanciamentoComponentMoved(evt);
            }
        });
        txtNomeFinanciamento.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNomeFinanciamentoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNomeFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyTyped(evt);
            }
        });

        jLabel2.setText("RG:");

        jLabel3.setText("CPF:");

        jLabel4.setText("CEP:");

        txtCEPFinanciamento.setPreferredSize(new java.awt.Dimension(90, 22));
        txtCEPFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPFinanciamentoActionPerformed(evt);
            }
        });
        txtCEPFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCEPFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCEPFinanciamentoKeyReleased(evt);
            }
        });

        jLabel5.setText("*ENDEREÇO:");

        txtEnderecoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoFinanciamentoKeyReleased(evt);
            }
        });

        jLabel6.setText("*BAIRRO:");

        txtBairroFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroFinanciamentoKeyReleased(evt);
            }
        });

        jLabel7.setText("*NÚMERO:");

        txtNumeroFinanciamento.setPreferredSize(new java.awt.Dimension(77, 22));
        txtNumeroFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroFinanciamentoKeyReleased(evt);
            }
        });

        jLabel8.setText("MUNICÍPIO:");

        jLabel9.setText("UF:");

        cbCidadeFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ribeirao Preto" }));
        cbCidadeFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCidadeFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbUFFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo" }));
        cbUFFinanciamento.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbUFFinanciamentoComponentAdded(evt);
            }
        });
        cbUFFinanciamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFFinanciamentoItemStateChanged(evt);
            }
        });
        cbUFFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbUFFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        try {
            txtRgFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRgFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRgFinanciamentoKeyPressed(evt);
            }
        });

        jLabel25.setText("*Telefone:");

        try {
            txtWhatsappFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtWhatsappFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWhatsappFinanciamentoKeyPressed(evt);
            }
        });

        jLabel26.setText("Whatsapp:");

        try {
            txtTelefoneFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneFinanciamentoKeyPressed(evt);
            }
        });

        txtCPFFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFinanciamentoFocusLost(evt);
            }
        });
        txtCPFFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFFinanciamentoKeyPressed(evt);
            }
        });

        jLabel28.setText("COMPL:");

        txtComplementoFinanciamento.setPreferredSize(new java.awt.Dimension(90, 22));
        txtComplementoFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoFinanciamentoActionPerformed(evt);
            }
        });
        txtComplementoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComplementoFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoFinanciamentoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeFinanciamento)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtCEPFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecoFinanciamento)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtBairroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtComplementoFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(txtWhatsappFinanciamento))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbCidadeFinanciamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbUFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtCEPFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel28)
                    .addComponent(txtComplementoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbCidadeFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtWhatsappFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(243, 245, 251));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Financiamento"));

        jLabel10.setText("*DATA:");

        dtFinanciamento.setDateFormatString("dd'-'MM'-'yyyy");
        dtFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dtFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel11.setText("*QTD. PARCELAS:");

        cbQtdParcelasFinanciamento.setEditable(true);
        cbQtdParcelasFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "6", "10", "12", "18", "24", "30", "36", "42", "48", "50", "60", "72", " " }));

        jLabel12.setText("*VALOR PARCELA:");

        jLabel13.setText("*VALOR VEÍCULO:");

        jLabel14.setText("VALOR ENTRADA:");

        jLabel15.setText("*DIA DE VENCIMENTO: ");

        cbDiaVencimentoFinanciamento.setEditable(true);
        cbDiaVencimentoFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20", "25" }));

        txtValVeiculoFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValVeiculoFinanciamento.setText("0,00");
        txtValVeiculoFinanciamento.setToolTipText("");
        txtValVeiculoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValVeiculoFinanciamentoKeyPressed(evt);
            }
        });

        txtValParcelaFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValParcelaFinanciamento.setText("0,00");
        txtValParcelaFinanciamento.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValParcelaFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValParcelaFinanciamentoKeyPressed(evt);
            }
        });

        txtValEntradafinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValEntradafinanciamento.setText("0,00");
        txtValEntradafinanciamento.setToolTipText("");
        txtValEntradafinanciamento.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValEntradafinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValEntradafinanciamentoActionPerformed(evt);
            }
        });
        txtValEntradafinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValEntradafinanciamentoKeyPressed(evt);
            }
        });

        txtObsFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObsFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtObsFinanciamentoKeyReleased(evt);
            }
        });

        jLabel24.setText("OBS:");

        jLabel27.setText("Ficha");

        txtFicha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtFicha.setMaximumSize(new java.awt.Dimension(64, 22));
        txtFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFichaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtObsFinanciamento))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dtFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtValVeiculoFinanciamento)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtValEntradafinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbDiaVencimentoFinanciamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel27)
                        .addComponent(txtFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtValEntradafinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtValVeiculoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbDiaVencimentoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObsFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(243, 245, 251));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Veículo"));

        jLabel16.setText("MARCA:");

        jLabel17.setText("MODELO:");

        jLabel18.setText("RENAVAM:");

        jLabel19.setText("CHASSI:");

        jLabel20.setText("PLACA:");

        jLabel21.setText("ANO:");

        jLabel23.setText("COR:");

        txtModeloEntrada.setEditable(false);

        txtMarcaEntrada.setEditable(false);

        txtRenavamEntrada.setEditable(false);

        txtChassiEntrada.setEditable(false);

        txtPlacaEntrada.setEditable(false);

        cbAnoEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbAnoEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbCorEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDE", "AMARELO", "PRETO", "CINZA", "AZUL", "BRANCO", "CHUMBO", "PRATA", "VINHO", "BEGE", "VERMELHO", " " }));
        cbCorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChassiEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenavamEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModeloEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarcaEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMarcaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtRenavamEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChassiEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFinanciamentoActionPerformed

    try{
        String[] fields = {
            this.txtNomeFinanciamento.getText(),
            this.txtEnderecoFinanciamento.getText(),
            this.txtBairroFinanciamento.getText(),
            this.txtNumeroFinanciamento.getText(),
            this.txtComplementoFinanciamento.getText(),
            this.txtTelefoneFinanciamento.getText(),
            this.dtFinanciamento.getDate().toString(),
            this.txtValParcelaFinanciamento.getText(),
            this.txtValVeiculoFinanciamento.getText(),
            this.cbQtdParcelasFinanciamento.getSelectedItem().toString(),
            this.cbDiaVencimentoFinanciamento.getSelectedItem().toString()
        };

        if( !Validacao.checkFieldsFormFinanciamento(fields)){
           JOptionPane.showMessageDialog(this,"preencha todos os campos *Obrigatórios");
           return;
        }

        int id_uf = EstadoDB.searchIdStateByName(this.cbUFFinanciamento.getSelectedItem().toString());
        int id_municipio = MunicipioDB.searchIdByCidade(this.cbCidadeFinanciamento.getSelectedItem().toString(), id_uf);
        
        //Dados do cliente para inserir no banco
        Cliente cliente = new Cliente();
        cliente.setNome(this.txtNomeFinanciamento.getText());
        cliente.setRg(this.txtRgFinanciamento.getText());
        cliente.setCpf(this.txtCPFFinanciamento.getText());
        cliente.setCep(this.txtCEPFinanciamento.getText());
        cliente.setEndereco(this.txtEnderecoFinanciamento.getText());
        cliente.setBairro(this.txtBairroFinanciamento.getText());
        cliente.setNumero(Integer.valueOf(this.txtNumeroFinanciamento.getText()));        
        cliente.setId_municipio(id_municipio);
        cliente.setUsuario(this.usuario.getUsuario());
        cliente.setWhatsapp(this.txtWhatsappFinanciamento.getText());
        cliente.setTelefone(this.txtTelefoneFinanciamento.getText());
        cliente.setComplemento(this.txtComplementoFinanciamento.getText());
        int id_cliente = ClienteDB.save(cliente);
        
        // inserir financiamento                
        Financiamento financiamento = new Financiamento(                        
            new java.sql.Date(this.dtFinanciamento.getDate().getTime()),
            Integer.valueOf(this.txtFicha.getText()),
            Double.valueOf(this.txtValParcelaFinanciamento.getText().replace(",", ".")),
            Double.valueOf(this.txtValEntradafinanciamento.getText().replace(",",".")),
            Double.valueOf(this.txtValVeiculoFinanciamento.getText().replace(",", ".")),
            Integer.valueOf(this.cbQtdParcelasFinanciamento.getSelectedItem().toString()),
            Integer.valueOf(this.cbDiaVencimentoFinanciamento.getSelectedItem().toString()),
            id_cliente,
            this.txtObsFinanciamento.getText()
        );
        int id_financiamento = FinanciamentoDB.save(financiamento);
        
        //registrar as parcelas          
        int numParcelas = financiamento.getNum_parcelas();        
        LocalDate hoje = LocalDate.now();
        java.sql.Date  data;
        Parcelamento parcela;
        for( int i = 1; i <= numParcelas; i++){
           data = Date.valueOf(hoje.plusMonths(i).withDayOfMonth(financiamento.getDia_vencimento()));
           parcela = new Parcelamento(null,null, id_financiamento,data, false);
           ParcelamentoDB.save(parcela);
        }                    
                    
        //realizar a saída do veiculo
        SaidaVeiculo saida = 
            new SaidaVeiculo(
                new java.sql.Date(dtFinanciamento.getDate().getTime()), 
                usuario.getUsuario(), 
                id_cliente, 
                entrada.getId(), 
                id_financiamento
            );
        SaidaVeiculoDB.save(saida);
        JOptionPane.showMessageDialog(this, "Registrado com sucesso!"); 
        
        //Opção de imprimir ficha
        PrinterJob job = PrinterJob.getPrinterJob();  
        if( JOptionPane.showConfirmDialog(rootPane, "Deja impirmir a ficha?") == JOptionPane.YES_OPTION  ){  
              Financiamento f = FinanciamentoDB.buscaPorId(id_financiamento);
              job.setPrintable(new PrintingFichaFrenteFinanciamento(f));
              boolean doPrint = job.printDialog();
              if (doPrint) job.print();
          }
        //imprimir verso da ficha
          if( JOptionPane.showConfirmDialog(rootPane, "Deja impirmir o verso da ficha?") == JOptionPane.YES_OPTION  ){                               
              job.setPrintable(new PrintingFichaVersoFinanciamento(FinanciamentoDB.buscaPorId(id_financiamento)));
              boolean doPrint = job.printDialog();
                  if (doPrint) job.print();                           
          }
    }catch(PrinterException | NullPointerException ex){
        JOptionPane.showMessageDialog(null, ex.getMessage());
    }
        
    }//GEN-LAST:event_btnSalvarFinanciamentoActionPerformed

    private void btnImprimirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirEntradaActionPerformed

    private void btnExcluirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEntradaActionPerformed

    private void btnLimparFormularioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaActionPerformed
       for(Component c: this.jPanel5.getComponents()){
         if( c instanceof JTextField || c instanceof JFormattedTextField){
             ((JTextField) c).setText("");
         }
       }
       
       for(Component c : this.jPanel6.getComponents()){
           if( c instanceof JTextField || c instanceof JFormattedTextField){
             ((JTextField) c).setText("");
         }
       }
        
    }//GEN-LAST:event_btnLimparFormularioEntradaActionPerformed

    private void txtPesquisarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarPlacaActionPerformed
        // TODO add your handling code here:
        this.txtPesquisarPlaca.setText(this.txtPesquisarPlaca.getText().toUpperCase());
    }//GEN-LAST:event_txtPesquisarPlacaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        Financiamento.janelaNovoFinanciamento = true;
        System.out.println(Financiamento.janelaNovoFinanciamento);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtPesquisarPlacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarPlacaMouseClicked
        //recuperando os dados do formulario
        
        
        
        
    }//GEN-LAST:event_txtPesquisarPlacaMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        Financiamento.janelaNovoFinanciamento = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        Financiamento.janelaNovoFinanciamento = true;
    
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
        Financiamento.janelaNovoFinanciamento = false;
   
    }//GEN-LAST:event_formAncestorRemoved

    private void btnLimparFormularioEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnLimparFormularioEntradaMouseClicked

    private void cbUFFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoAncestorAdded
        // TODO add your handling code here:
        List<Estado> estados;

        estados = EstadoDB.selectAll();

        for(Estado estado: estados){
            this.cbUFFinanciamento.addItem(estado.getNome());
        }
    }//GEN-LAST:event_cbUFFinanciamentoAncestorAdded

    private void cbUFFinanciamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoItemStateChanged
        // TODO add your handling code here:
        List<Municipio> municipios;
        municipios = MunicipioDB.selectAllByState(cbUFFinanciamento.getSelectedItem().toString());
        this.cbCidadeFinanciamento.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeFinanciamento.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFFinanciamentoItemStateChanged

    private void cbUFFinanciamentoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoComponentAdded
        // TODO add your handling code here:
        List<Municipio> municipios;
        municipios = MunicipioDB.selectAllByState(cbUFFinanciamento.getSelectedItem().toString());
        this.cbCidadeFinanciamento.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeFinanciamento.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFFinanciamentoComponentAdded

    private void cbCidadeFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCidadeFinanciamentoAncestorAdded
        // TODO add your handling code here:
        List<Municipio> municipios;

        municipios = MunicipioDB.selectAllByState("São Paulo");
        for(Municipio municipio: municipios){
            this.cbCidadeFinanciamento.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbCidadeFinanciamentoAncestorAdded

    private void txtNumeroFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFinanciamentoKeyReleased
        // TODO add your handling code here:

        if( !Character.isDigit(evt.getKeyChar())){
            if( this.txtNumeroFinanciamento.getText().length() > 0){
                this.txtNumeroFinanciamento.setText(this.txtNumeroFinanciamento.getText().substring(0, this.txtNumeroFinanciamento.getText().length()-1));
                this.txtNumeroFinanciamento.setToolTipText("Digite apenas números");
                JOptionPane.showMessageDialog(this, "Digite apenas números", "Error", JOptionPane.WARNING_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_txtNumeroFinanciamentoKeyReleased

    private void txtBairroFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtBairroFinanciamento.setText(Validacao.textoSemAcentuacaoEallUpperCase(this.txtBairroFinanciamento.getText(), "ÀÈÌÒÙÁÉÍÓÚÂÊÎÔÛÃÕÇ"));
    }//GEN-LAST:event_txtBairroFinanciamentoKeyReleased

    private void txtEnderecoFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtEnderecoFinanciamento.setText(Validacao.textoSemAcentuacaoEallUpperCase(this.txtEnderecoFinanciamento.getText(), "ÀÈÌÒÙÁÉÍÓÚÂÊÎÔÛÃÕÇ"));
    }//GEN-LAST:event_txtEnderecoFinanciamentoKeyReleased

    private void txtCEPFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoKeyReleased
        // TODO add your handling code here:

        

    }//GEN-LAST:event_txtCEPFinanciamentoKeyReleased

    private void txtCEPFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPFinanciamentoActionPerformed

    private void txtNomeFinanciamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomeFinanciamentoKeyTyped

    private void txtNomeFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtNomeFinanciamento.setText(Validacao.textoSemAcentuacaoEallUpperCase(this.txtNomeFinanciamento.getText(), "ÀÈÌÒÙÁÉÍÓÚÂÊÎÔÛÃÕÇ"));

    }//GEN-LAST:event_txtNomeFinanciamentoKeyReleased

    private void txtNomeFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtNomeFinanciamento.getText().length() > 99 ){
            this.txtNomeFinanciamento.setText( this.txtNomeFinanciamento.getText().substring(0, 99));
        }

    }//GEN-LAST:event_txtNomeFinanciamentoKeyPressed

    private void txtNomeFinanciamentoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoCaretPositionChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomeFinanciamentoCaretPositionChanged

    private void txtNomeFinanciamentoComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoComponentMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomeFinanciamentoComponentMoved

    private void txtNomeFinanciamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomeFinanciamentoFocusGained

    private void txtNomeFinanciamentoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomeFinanciamentoCaretUpdate

    private void dtFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dtFinanciamentoAncestorAdded
        // TODO add your handling code here:
         java.util.Date data = new java.util.Date();
        this.dtFinanciamento.setDate(data);
    }//GEN-LAST:event_dtFinanciamentoAncestorAdded

    private void cbAnoEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbAnoEntradaAncestorAdded
        // TODO add your handling code here:
        for (int i = 1950; i < 2061; i++) {
            this.cbAnoEntrada.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_cbAnoEntradaAncestorAdded

    private void cbCorEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCorEntradaKeyTyped

    private void txtPesquisarPlacaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarPlacaMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPesquisarPlacaMouseReleased

    private void btnPesquisarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaActionPerformed
        // TODO add your handling code here:
        this.entrada = EntradaVeiculoDB.procuraVeiculoDisponivelPorPlaca(this.txtPesquisarPlaca.getText());
            if(this.entrada != null){                    
                   this.txtMarcaEntrada.setText(this.entrada.getMarca());
                   this.txtModeloEntrada.setText(this.entrada.getModelo());
                   this.txtRenavamEntrada.setText(this.entrada.getRenavam());
                   this.txtChassiEntrada.setText(this.entrada.getChassi());
                   this.txtPlacaEntrada.setText(this.entrada.getPlaca());
                   this.cbAnoEntrada.setSelectedItem(this.entrada.getAno());
                   this.cbCorEntrada.setSelectedItem(this.entrada.getCor());                   
                }else{ 
                   this.txtMarcaEntrada.setText("");
                   this.txtModeloEntrada.setText("");
                   this.txtRenavamEntrada.setText("");
                   this.txtChassiEntrada.setText("");
                   this.txtPlacaEntrada.setText("");
                   this.cbAnoEntrada.setSelectedItem("");
                   this.cbCorEntrada.setSelectedItem("");   
                    JOptionPane.showMessageDialog(this, "Nenhum resultado encontrado");
                 }
    }//GEN-LAST:event_btnPesquisarEntradaActionPerformed

    private void txtPesquisarPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarPlacaKeyReleased
        // TODO add your handling code here:
        this.txtPesquisarPlaca.setText(this.txtPesquisarPlaca.getText().toUpperCase());
    }//GEN-LAST:event_txtPesquisarPlacaKeyReleased

    private void txtValEntradafinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValEntradafinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValEntradafinanciamentoActionPerformed

    private void txtRgFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRgFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtRgFinanciamento.getText().length() > 12 ){
            this.txtRgFinanciamento.setText( this.txtRgFinanciamento.getText().substring(0, 12));
        }
    }//GEN-LAST:event_txtRgFinanciamentoKeyPressed

    private void txtCEPFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoKeyPressed
        // TODO add your handling code here:
        
        
        if( !Character.isDigit(evt.getKeyChar())){
            if( this.txtCEPFinanciamento.getText().length() > 0){
                this.txtCEPFinanciamento.setText(this.txtCEPFinanciamento.getText().substring(0, this.txtCEPFinanciamento.getText().length()-1));
                this.txtCEPFinanciamento.setToolTipText("Digite apenas números");
            }
        }else{
            int  letraLen = this.txtCEPFinanciamento.getText().length();
            if( letraLen == 5){
                this.txtCEPFinanciamento.setText(this.txtCEPFinanciamento.getText() + "-");
            }

            if(letraLen > 8 ){
                this.txtCEPFinanciamento.setText(this.txtCEPFinanciamento.getText().substring(0, 8));
            }

        }
    }//GEN-LAST:event_txtCEPFinanciamentoKeyPressed

    private void txtEnderecoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtEnderecoFinanciamento.getText().length() > 99 ){
            this.txtEnderecoFinanciamento.setText( this.txtEnderecoFinanciamento.getText().substring(0, 99));
        }
    }//GEN-LAST:event_txtEnderecoFinanciamentoKeyPressed

    private void txtBairroFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtBairroFinanciamento.getText().length() > 99 ){
            this.txtBairroFinanciamento.setText( this.txtBairroFinanciamento.getText().substring(0, 99));
        }
    }//GEN-LAST:event_txtBairroFinanciamentoKeyPressed

    private void txtWhatsappFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhatsappFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtWhatsappFinanciamento.getText().length() > 15 ){
            this.txtWhatsappFinanciamento.setText( this.txtWhatsappFinanciamento.getText().substring(0, 15));
        }
    }//GEN-LAST:event_txtWhatsappFinanciamentoKeyPressed

    private void txtTelefoneFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtTelefoneFinanciamento.getText().length() > 15 ){
            this.txtTelefoneFinanciamento.setText( this.txtTelefoneFinanciamento.getText().substring(0, 15));
        }
    }//GEN-LAST:event_txtTelefoneFinanciamentoKeyPressed

    private void txtValParcelaFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValParcelaFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtValParcelaFinanciamento.getText().length() > 11 ){
            this.txtValParcelaFinanciamento.setText( this.txtValParcelaFinanciamento.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtValParcelaFinanciamentoKeyPressed

    private void txtValEntradafinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValEntradafinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtValEntradafinanciamento.getText().length() > 11 ){
            this.txtValEntradafinanciamento.setText( this.txtValEntradafinanciamento.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtValEntradafinanciamentoKeyPressed

    private void txtValVeiculoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValVeiculoFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtValVeiculoFinanciamento.getText().length() > 11 ){
            this.txtValVeiculoFinanciamento.setText( this.txtValVeiculoFinanciamento.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtValVeiculoFinanciamentoKeyPressed

    private void txtObsFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtObsFinanciamento.getText().length() > 199 ){
            this.txtObsFinanciamento.setText( this.txtObsFinanciamento.getText().substring(0, 199));
        }
    }//GEN-LAST:event_txtObsFinanciamentoKeyPressed

    private void txtCPFFinanciamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoFocusLost
        // TODO add your handling code here:
        if( this.txtCPFFinanciamento.getText().length() < 11 && !this.txtCPFFinanciamento.getText().isBlank() ){
             JOptionPane.showMessageDialog(this, "CPF inválido");
            this.txtCPFFinanciamento.requestFocus();
          
        }else if(!this.txtCPFFinanciamento.getText().isBlank()&& this.txtCPFFinanciamento.getText().length() == 11 ){
                if( Validacao.validaCPF(this.txtCPFFinanciamento.getText()) == false ){
                    JOptionPane.showMessageDialog(this, "CPF inválido");             
                    this.txtCPFFinanciamento.requestFocus();
                    this.txtCPFFinanciamento.setText("");
                }
        }
       
        
    }//GEN-LAST:event_txtCPFFinanciamentoFocusLost

    private void txtCPFFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtCPFFinanciamento.getText().length() > 10 ){
            this.txtCPFFinanciamento.setText( this.txtCPFFinanciamento.getText().substring(0, 10));
        }
    }//GEN-LAST:event_txtCPFFinanciamentoKeyPressed

    private void txtFichaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFichaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFichaKeyPressed

    private void txtObsFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtObsFinanciamento.setText(Validacao.textoSemAcentuacaoEallUpperCase(this.txtObsFinanciamento.getText(), "ÀÈÌÒÙÁÉÍÓÚÂÊÎÔÛÃÕÇ"));
    }//GEN-LAST:event_txtObsFinanciamentoKeyReleased

    private void txtComplementoFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoFinanciamentoActionPerformed

    private void txtComplementoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoFinanciamentoKeyPressed

    private void txtComplementoFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtComplementoFinanciamento.setText(this.txtComplementoFinanciamento.getText().toUpperCase());
    }//GEN-LAST:event_txtComplementoFinanciamentoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirEntrada;
    private javax.swing.JButton btnImprimirEntrada;
    private javax.swing.JButton btnLimparFormularioEntrada;
    private javax.swing.JButton btnPesquisarEntrada;
    private javax.swing.JButton btnSalvarFinanciamento;
    private javax.swing.JComboBox<String> cbAnoEntrada;
    private javax.swing.JComboBox<String> cbCidadeFinanciamento;
    private javax.swing.JComboBox<String> cbCorEntrada;
    private javax.swing.JComboBox<String> cbDiaVencimentoFinanciamento;
    private javax.swing.JComboBox<String> cbQtdParcelasFinanciamento;
    private javax.swing.JComboBox<String> cbUFFinanciamento;
    private com.toedter.calendar.JDateChooser dtFinanciamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtBairroFinanciamento;
    private javax.swing.JTextField txtCEPFinanciamento;
    private javax.swing.JTextField txtCPFFinanciamento;
    private javax.swing.JTextField txtChassiEntrada;
    private javax.swing.JTextField txtComplementoFinanciamento;
    private javax.swing.JTextField txtEnderecoFinanciamento;
    private javax.swing.JFormattedTextField txtFicha;
    private javax.swing.JTextField txtMarcaEntrada;
    private javax.swing.JTextField txtModeloEntrada;
    private javax.swing.JTextField txtNomeFinanciamento;
    private javax.swing.JTextField txtNumeroFinanciamento;
    private javax.swing.JTextField txtObsFinanciamento;
    private javax.swing.JTextField txtPesquisarPlaca;
    private javax.swing.JTextField txtPlacaEntrada;
    private javax.swing.JTextField txtRenavamEntrada;
    private javax.swing.JFormattedTextField txtRgFinanciamento;
    private javax.swing.JFormattedTextField txtTelefoneFinanciamento;
    private javax.swing.JFormattedTextField txtValEntradafinanciamento;
    private javax.swing.JFormattedTextField txtValParcelaFinanciamento;
    private javax.swing.JFormattedTextField txtValVeiculoFinanciamento;
    private javax.swing.JFormattedTextField txtWhatsappFinanciamento;
    // End of variables declaration//GEN-END:variables
}
