/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.wesleycoelho.view;

import com.wesleycoelho.controllers.jdbc.conn.ConnectionFactory;
import com.wesleycoelho.controllers.jdbc.conn.EntradaVeiculoDB;
import com.wesleycoelho.controllers.jdbc.conn.EstadoDB;
import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Usuario;
import javax.swing.JOptionPane;
import com.wesleycoelho.controllers.jdbc.conn.MunicipioDB;
import com.wesleycoelho.model.Estado;
import com.wesleycoelho.model.Municipio;
import com.wesleycoelho.model.PrintingEntradaVeiculo;
import com.wesleycoelho.model.Validacao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.awt.print.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.sql.Date;



/**
 *
 * @author Wesley
 */
public class FormNovaEntrada extends javax.swing.JInternalFrame {
    Usuario usuario = new Usuario();
    /**
     * Creates new form FormNovaEntrada
     * @param user
     */
    public FormNovaEntrada(Usuario user) {
        this.usuario = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSalvarEntrada = new javax.swing.JButton();
        btnImprimirEntrada = new javax.swing.JButton();
        btnExcluirEntrada = new javax.swing.JButton();
        btnLimparFormularioEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPesquisarEntrada = new javax.swing.JButton();
        txtPesquisarEntrada = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtModeloEntrada = new javax.swing.JTextField();
        txtMarcaEntrada = new javax.swing.JTextField();
        txtRenavamEntrada = new javax.swing.JTextField();
        txtChassiEntrada = new javax.swing.JTextField();
        txtPlacaEntrada = new javax.swing.JTextField();
        cbAnoEntrada = new javax.swing.JComboBox<>();
        cbCorEntrada = new javax.swing.JComboBox<>();
        cbCidadeEntrada = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbUFEntrada = new javax.swing.JComboBox<>();
        txtDataEntrada = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtProprietarioEntrada = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTelefoneEntrada = new javax.swing.JFormattedTextField();
        txtWhatsappEntrada = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nova Entrada de veículo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-car-16_1.png"))); // NOI18N
        setVisible(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSalvarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-16.png"))); // NOI18N
        btnSalvarEntrada.setToolTipText("Salvar");
        btnSalvarEntrada.setFocusable(false);
        btnSalvarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvarEntrada);

        btnImprimirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-print-16.png"))); // NOI18N
        btnImprimirEntrada.setToolTipText("Imprimir");
        btnImprimirEntrada.setEnabled(false);
        btnImprimirEntrada.setFocusable(false);
        btnImprimirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirEntrada);

        btnExcluirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-trash-16.png"))); // NOI18N
        btnExcluirEntrada.setToolTipText("Excluir");
        btnExcluirEntrada.setEnabled(false);
        btnExcluirEntrada.setFocusable(false);
        btnExcluirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirEntrada);

        btnLimparFormularioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-broom-16.png"))); // NOI18N
        btnLimparFormularioEntrada.setToolTipText("Limpar Formulário");
        btnLimparFormularioEntrada.setFocusable(false);
        btnLimparFormularioEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFormularioEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFormularioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparFormularioEntradaMouseClicked(evt);
            }
        });
        btnLimparFormularioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormularioEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimparFormularioEntrada);
        jToolBar1.add(jSeparator1);

        btnPesquisarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-16.png"))); // NOI18N
        btnPesquisarEntrada.setEnabled(false);
        btnPesquisarEntrada.setFocusable(false);
        btnPesquisarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPesquisarEntrada);

        txtPesquisarEntrada.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisarEntrada.setText("Digite a Placa");
        txtPesquisarEntrada.setEnabled(false);
        txtPesquisarEntrada.setMaximumSize(new java.awt.Dimension(200, 20));
        txtPesquisarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarEntradaMouseClicked(evt);
            }
        });
        txtPesquisarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(txtPesquisarEntrada);

        jPanel5.setBackground(new java.awt.Color(243, 245, 251));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Veículo"));

        jLabel4.setText("MARCA:");

        jLabel5.setText("MODELO:");

        jLabel6.setText("RENAVAM:");

        jLabel7.setText("CHASSI:");

        jLabel8.setText("PLACA:");

        jLabel9.setText("ANO:");

        jLabel10.setText("DATA:");

        jLabel11.setText("COR:");

        jLabel12.setText("CIDADE:");

        txtModeloEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModeloEntradaKeyReleased(evt);
            }
        });

        txtMarcaEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarcaEntradaKeyReleased(evt);
            }
        });

        txtRenavamEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRenavamEntradaKeyReleased(evt);
            }
        });

        txtChassiEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChassiEntradaKeyReleased(evt);
            }
        });

        txtPlacaEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaEntradaKeyReleased(evt);
            }
        });

        cbAnoEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbAnoEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbCorEntrada.setEditable(true);
        cbCorEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDE", "AMARELO", "PRETO", "CINZA", "AZUL", "BRANCO", "CHUMBO", "PRATA", "VINHO", "BEGE", "VERMELHO", " " }));
        cbCorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyTyped(evt);
            }
        });

        cbCidadeEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ribeirao Preto" }));
        cbCidadeEntrada.setAutoscrolls(true);
        cbCidadeEntrada.setDoubleBuffered(true);
        cbCidadeEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCidadeEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel16.setText("UF:");

        cbUFEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo" }));
        cbUFEntrada.setAutoscrolls(true);
        cbUFEntrada.setDoubleBuffered(true);
        cbUFEntrada.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbUFEntradaComponentAdded(evt);
            }
        });
        cbUFEntrada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFEntradaItemStateChanged(evt);
            }
        });
        cbUFEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbUFEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtDataEntrada.setDateFormatString("d '/' MMM '/' y");
        txtDataEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtDataEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChassiEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenavamEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModeloEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarcaEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbCidadeEntrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbUFEntrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMarcaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRenavamEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChassiEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11)
                        .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbCidadeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbUFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jPanel6.setBackground(new java.awt.Color(243, 245, 251));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        jLabel13.setText("PROPRIETÁRIO:");

        txtProprietarioEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProprietarioEntradaKeyReleased(evt);
            }
        });

        jLabel14.setText("TELEFONE:");

        jLabel15.setText("WHATSAPP:");

        try {
            txtTelefoneEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtWhatsappEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtTelefoneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtWhatsappEntrada))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtProprietarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtProprietarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtWhatsappEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtTelefoneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEntradaActionPerformed

        boolean fields = Validacao.checkFieldsFormFinanciamento(new String[]{            
            this.txtPlacaEntrada.getText(),            
        });
       try{  
            if ( fields  ==  false) throw new RuntimeException("Preencha todos os campos!");         
            
            String nomeMunicipio, nome_Uf;
            int id_Uf;
            
            EntradaVeiculo entradaVeiculo = new EntradaVeiculo();
            entradaVeiculo.setNome_proprietario(this.txtProprietarioEntrada.getText());
            entradaVeiculo.setTelefone(this.txtTelefoneEntrada.getText());
            entradaVeiculo.setWhatsapp(this.txtWhatsappEntrada.getText());             
            entradaVeiculo.setData_entrada(new java.sql.Date(this.txtDataEntrada.getDate().getTime()));
            entradaVeiculo.setMarca(this.txtMarcaEntrada.getText());
            entradaVeiculo.setModelo(this.txtModeloEntrada.getText());
            entradaVeiculo.setRenavam(this.txtRenavamEntrada.getText());
            entradaVeiculo.setChassi(this.txtChassiEntrada.getText());
            entradaVeiculo.setPlaca(this.txtPlacaEntrada.getText());
            entradaVeiculo.setCor(this.cbCorEntrada.getSelectedItem().toString());
            nomeMunicipio = this.cbCidadeEntrada.getSelectedItem().toString();
            nome_Uf = this.cbUFEntrada.getSelectedItem().toString();
            List<Estado> estados = EstadoDB.searchByName(nome_Uf);
            id_Uf = estados.getFirst().getId();              
            String sql = "SELECT * FROM municipio WHERE cidade = '"+nomeMunicipio+"' AND id_uf = "+id_Uf+";";
            Connection conn = ConnectionFactory.getConexao();
                    Statement stmt = conn.createStatement();
                    ResultSet resultSet = stmt.executeQuery(sql);            
                    while(resultSet.next()){               
                       entradaVeiculo.setId_municipio(resultSet.getInt("id"));
                        }
                    ConnectionFactory.close(conn, stmt, resultSet);
            entradaVeiculo.setAno(this.cbAnoEntrada.getSelectedItem().toString());
            entradaVeiculo.setUsuario(this.usuario.getUsuario());  
            EntradaVeiculoDB.save(entradaVeiculo);
            JOptionPane.showMessageDialog(this, "Nova entrada de veículo cadastrada com sucesso!");
            int imprimirFicha = JOptionPane.showConfirmDialog(rootPane, "Deja impirmir a ficha?");
                if( imprimirFicha == 0  ){
                    PrinterJob job = PrinterJob.getPrinterJob();
                    job.setPrintable(new PrintingEntradaVeiculo(entradaVeiculo));
                    boolean doPrint = job.printDialog();
                        if (doPrint) job.print();
                }
        }catch(RuntimeException | PrinterException | SQLException ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
     
 
        
        
        
        
        
    }//GEN-LAST:event_btnSalvarEntradaActionPerformed

    private void btnImprimirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEntradaActionPerformed

        
        
    }//GEN-LAST:event_btnImprimirEntradaActionPerformed

    private void btnExcluirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEntradaActionPerformed

    private void btnLimparFormularioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparFormularioEntradaActionPerformed

    private void txtPesquisarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarEntradaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        EntradaVeiculo.janelaNovaEntrada = true;
        System.out.println(EntradaVeiculo.janelaNovaEntrada);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtPesquisarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarEntradaMouseClicked
        //recuperando os dados do formulario
        
        
        
        
    }//GEN-LAST:event_txtPesquisarEntradaMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        EntradaVeiculo.janelaNovaEntrada = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        EntradaVeiculo.janelaNovaEntrada = true;
    
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
        EntradaVeiculo.janelaNovaEntrada = false;
   
    }//GEN-LAST:event_formAncestorRemoved

    private void btnLimparFormularioEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaMouseClicked
        // TODO add your handling code here:
        this.txtChassiEntrada.setText("");
        this.txtMarcaEntrada.setText("");
        this.txtModeloEntrada.setText("");
        this.txtPlacaEntrada.setText("");
        this.txtRenavamEntrada.setText("");
        this.txtProprietarioEntrada.setText("");
        this.txtTelefoneEntrada.setText("");
        this.txtWhatsappEntrada.setText("");
        
    }//GEN-LAST:event_btnLimparFormularioEntradaMouseClicked

    private void txtProprietarioEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProprietarioEntradaKeyReleased
        // TODO add your handling code here:
        this.txtProprietarioEntrada.setText(this.txtProprietarioEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtProprietarioEntradaKeyReleased

    private void cbUFEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbUFEntradaAncestorAdded
        // TODO add your handling code here:
        List<Estado> estados;

        estados = EstadoDB.selectAll();

        for(Estado estado: estados){
            this.cbUFEntrada.addItem(estado.getNome());
        }
    }//GEN-LAST:event_cbUFEntradaAncestorAdded

    private void cbUFEntradaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFEntradaItemStateChanged
        // TODO add your handling code here:
        List<Municipio> municipios;
        municipios = MunicipioDB.selectAllByState(cbUFEntrada.getSelectedItem().toString());
        this.cbCidadeEntrada.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeEntrada.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFEntradaItemStateChanged

    private void cbUFEntradaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbUFEntradaComponentAdded
        // TODO add your handling code here:
        List<Municipio> municipios;
        municipios = MunicipioDB.selectAllByState(cbUFEntrada.getSelectedItem().toString());
        this.cbCidadeEntrada.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeEntrada.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFEntradaComponentAdded

    private void cbCidadeEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCidadeEntradaAncestorAdded
        // TODO add your handling code here:
        List<Municipio> municipios;

        municipios = MunicipioDB.selectAllByState("São Paulo");
        for(Municipio municipio: municipios){
            this.cbCidadeEntrada.addItem(municipio.getNome());
        }

    }//GEN-LAST:event_cbCidadeEntradaAncestorAdded

    private void cbCorEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCorEntradaKeyTyped

    private void cbCorEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyReleased
        // TODO add your handling code here:
        this.cbCorEntrada.setSelectedItem(this.cbCorEntrada.getSelectedItem().toString().toUpperCase());
    }//GEN-LAST:event_cbCorEntradaKeyReleased

    private void cbAnoEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbAnoEntradaAncestorAdded
        // TODO add your handling code here:
        for (int i = 1950; i < 2061; i++) {
            this.cbAnoEntrada.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_cbAnoEntradaAncestorAdded

    private void txtPlacaEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaEntradaKeyReleased
        // TODO add your handling code here:
        this.txtPlacaEntrada.setText(this.txtPlacaEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtPlacaEntradaKeyReleased

    private void txtChassiEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChassiEntradaKeyReleased
        // TODO add your handling code here:
        this.txtChassiEntrada.setText(this.txtChassiEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtChassiEntradaKeyReleased

    private void txtRenavamEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRenavamEntradaKeyReleased
        // TODO add your handling code here:
        this.txtRenavamEntrada.setText(this.txtRenavamEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtRenavamEntradaKeyReleased

    private void txtMarcaEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaEntradaKeyReleased
        // TODO add your handling code here:
        this.txtMarcaEntrada.setText(this.txtMarcaEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtMarcaEntradaKeyReleased

    private void txtModeloEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloEntradaKeyReleased
        // TODO add your handling code here:
        this.txtModeloEntrada.setText(this.txtModeloEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtModeloEntradaKeyReleased

    private void txtDataEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtDataEntradaAncestorAdded
         java.util.Date data = new java.util.Date();
        this.txtDataEntrada.setDate(data);
    }//GEN-LAST:event_txtDataEntradaAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirEntrada;
    private javax.swing.JButton btnImprimirEntrada;
    private javax.swing.JButton btnLimparFormularioEntrada;
    private javax.swing.JButton btnPesquisarEntrada;
    private javax.swing.JButton btnSalvarEntrada;
    private javax.swing.JComboBox<String> cbAnoEntrada;
    private javax.swing.JComboBox<String> cbCidadeEntrada;
    private javax.swing.JComboBox<String> cbCorEntrada;
    private javax.swing.JComboBox<String> cbUFEntrada;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtChassiEntrada;
    private com.toedter.calendar.JDateChooser txtDataEntrada;
    private javax.swing.JTextField txtMarcaEntrada;
    private javax.swing.JTextField txtModeloEntrada;
    private javax.swing.JTextField txtPesquisarEntrada;
    private javax.swing.JTextField txtPlacaEntrada;
    private javax.swing.JTextField txtProprietarioEntrada;
    private javax.swing.JTextField txtRenavamEntrada;
    private javax.swing.JFormattedTextField txtTelefoneEntrada;
    private javax.swing.JFormattedTextField txtWhatsappEntrada;
    // End of variables declaration//GEN-END:variables
}
