/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.wesleycoelho.view;
import com.wesleycoelho.controllers.jdbc.conn.EstadoDB;
import com.wesleycoelho.controllers.jdbc.conn.FinanciamentoDB;
import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Usuario;
import javax.swing.JOptionPane;
import com.wesleycoelho.controllers.jdbc.conn.MunicipioDB;
import com.wesleycoelho.controllers.jdbc.conn.ParcelamentoDB;
import com.wesleycoelho.model.Cliente;
import com.wesleycoelho.model.DaoException;
import com.wesleycoelho.model.Estado;
import com.wesleycoelho.model.Financiamento;
import com.wesleycoelho.model.Municipio;
import com.wesleycoelho.model.PrintingFichaFrenteFinanciamento;
import com.wesleycoelho.model.PrintingFichaVersoFinanciamento;
import com.wesleycoelho.model.SaidaVeiculo;
import com.wesleycoelho.model.Validacao;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;





/**
 *
 * @author Wesley
 */
public class FormEditarFinanciamento extends javax.swing.JInternalFrame {
    Usuario usuario = new Usuario();
    EntradaVeiculo entrada;
    Cliente cliente;
    Financiamento financiamento;
    SaidaVeiculo saida;
    /**
     * Creates new form FormNovaEntrada
     */
    public FormEditarFinanciamento(Usuario user) {
        this.usuario = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSalvarFinanciamento = new javax.swing.JButton();
        btnImprimirFinanciamento = new javax.swing.JButton();
        btnExcluirEntrada = new javax.swing.JButton();
        btnLimparFormularioEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(5, 0));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0));
        cbOptionPesquisa = new javax.swing.JComboBox<>();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0));
        txtPesquisarFinanciamento = new javax.swing.JTextField();
        btnPesquisarFinanciamento = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtModeloEntrada = new javax.swing.JTextField();
        txtMarcaEntrada = new javax.swing.JTextField();
        txtRenavamEntrada = new javax.swing.JTextField();
        txtChassiEntrada = new javax.swing.JTextField();
        txtPlacaEntrada = new javax.swing.JTextField();
        cbAnoEntrada = new javax.swing.JComboBox<>();
        cbCorEntrada = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFinanciamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCEPFinanciamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEnderecoFinanciamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBairroFinanciamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroFinanciamento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbCidadeFinanciamento = new javax.swing.JComboBox<>();
        cbUFFinanciamento = new javax.swing.JComboBox<>();
        txtRgFinanciamento = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        txtWhatsappFinanciamento = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTelefoneFinanciamento = new javax.swing.JFormattedTextField();
        txtCPFFinanciamento = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtComplementoFinanciamento = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dtFinanciamento = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cbQtdParcelasFinanciamento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbDiaVencimentoFinanciamento = new javax.swing.JComboBox<>();
        txtValParcelaFinanciamento = new javax.swing.JFormattedTextField();
        txtObsFinanciamento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtFicha = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("EDITAR financiamento");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-car-16_1.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToolBar1.setMargin(new java.awt.Insets(0, 5, 0, 5));

        btnSalvarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-16.png"))); // NOI18N
        btnSalvarFinanciamento.setToolTipText("Salvar");
        btnSalvarFinanciamento.setFocusable(false);
        btnSalvarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarFinanciamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFinanciamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvarFinanciamento);

        btnImprimirFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-print-16.png"))); // NOI18N
        btnImprimirFinanciamento.setToolTipText("Imprimir");
        btnImprimirFinanciamento.setFocusable(false);
        btnImprimirFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirFinanciamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirFinanciamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirFinanciamento);

        btnExcluirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-trash-16.png"))); // NOI18N
        btnExcluirEntrada.setToolTipText("Excluir");
        btnExcluirEntrada.setEnabled(false);
        btnExcluirEntrada.setFocusable(false);
        btnExcluirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirEntrada);

        btnLimparFormularioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-broom-16.png"))); // NOI18N
        btnLimparFormularioEntrada.setToolTipText("Limpar Formulário");
        btnLimparFormularioEntrada.setEnabled(false);
        btnLimparFormularioEntrada.setFocusable(false);
        btnLimparFormularioEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFormularioEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFormularioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparFormularioEntradaMouseClicked(evt);
            }
        });
        btnLimparFormularioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormularioEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimparFormularioEntrada);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(filler2);
        jToolBar1.add(filler1);
        jToolBar1.add(filler3);

        cbOptionPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ficha" }));
        cbOptionPesquisa.setMaximumSize(new java.awt.Dimension(100, 22));
        jToolBar1.add(cbOptionPesquisa);
        jToolBar1.add(filler4);

        txtPesquisarFinanciamento.setToolTipText("Digite a placa");
        txtPesquisarFinanciamento.setDoubleBuffered(true);
        txtPesquisarFinanciamento.setMaximumSize(new java.awt.Dimension(200, 20));
        txtPesquisarFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarFinanciamentoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPesquisarFinanciamentoMouseReleased(evt);
            }
        });
        txtPesquisarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarFinanciamentoActionPerformed(evt);
            }
        });
        txtPesquisarFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarFinanciamentoKeyReleased(evt);
            }
        });
        jToolBar1.add(txtPesquisarFinanciamento);

        btnPesquisarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-16.png"))); // NOI18N
        btnPesquisarFinanciamento.setFocusable(false);
        btnPesquisarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarFinanciamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFinanciamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPesquisarFinanciamento);

        jPanel7.setBackground(new java.awt.Color(243, 245, 251));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Veículo"));

        jLabel16.setText("MARCA:");

        jLabel17.setText("MODELO:");

        jLabel18.setText("RENAVAM:");

        jLabel19.setText("CHASSI:");

        jLabel20.setText("PLACA:");

        jLabel21.setText("ANO:");

        jLabel23.setText("COR:");

        txtModeloEntrada.setEnabled(false);

        txtMarcaEntrada.setEnabled(false);

        txtRenavamEntrada.setEnabled(false);

        txtChassiEntrada.setEnabled(false);

        txtPlacaEntrada.setEnabled(false);

        cbAnoEntrada.setEditable(true);
        cbAnoEntrada.setEnabled(false);
        cbAnoEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbAnoEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbCorEntrada.setEditable(true);
        cbCorEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Amarelo", "Preto", "Cinza", "Azul", "Branco", "Chumbo", "Prata", "Vinho", "Bege", "Vermelho", " " }));
        cbCorEntrada.setEnabled(false);
        cbCorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChassiEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenavamEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModeloEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarcaEntrada))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMarcaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtRenavamEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChassiEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel5.setBackground(new java.awt.Color(243, 245, 251));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel1.setText("NOME:");

        txtNomeFinanciamento.setActionCommand("null");
        txtNomeFinanciamento.setVerifyInputWhenFocusTarget(false);
        txtNomeFinanciamento.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeFinanciamentoCaretUpdate(evt);
            }
        });
        txtNomeFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFinanciamentoFocusGained(evt);
            }
        });
        txtNomeFinanciamento.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtNomeFinanciamentoComponentMoved(evt);
            }
        });
        txtNomeFinanciamento.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNomeFinanciamentoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNomeFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyTyped(evt);
            }
        });

        jLabel2.setText("RG:");

        jLabel3.setText("CPF:");

        jLabel4.setText("CEP:");

        txtCEPFinanciamento.setPreferredSize(new java.awt.Dimension(90, 22));
        txtCEPFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPFinanciamentoActionPerformed(evt);
            }
        });
        txtCEPFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCEPFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCEPFinanciamentoKeyReleased(evt);
            }
        });

        jLabel5.setText("ENDEREÇO:");

        txtEnderecoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoFinanciamentoKeyReleased(evt);
            }
        });

        jLabel6.setText("BAIRRO:");

        txtBairroFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBairroFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroFinanciamentoKeyReleased(evt);
            }
        });

        jLabel7.setText("NÚMERO:");

        txtNumeroFinanciamento.setPreferredSize(new java.awt.Dimension(77, 22));
        txtNumeroFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroFinanciamentoKeyReleased(evt);
            }
        });

        jLabel8.setText("MUNICÍPIO:");

        jLabel9.setText("UF:");

        cbCidadeFinanciamento.setEditable(true);
        cbCidadeFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ribeirao Preto" }));
        cbCidadeFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCidadeFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbUFFinanciamento.setEditable(true);
        cbUFFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo" }));
        cbUFFinanciamento.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbUFFinanciamentoComponentAdded(evt);
            }
        });
        cbUFFinanciamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFFinanciamentoItemStateChanged(evt);
            }
        });
        cbUFFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbUFFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        try {
            txtRgFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRgFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRgFinanciamentoKeyPressed(evt);
            }
        });

        jLabel25.setText("Telefone:");

        try {
            txtWhatsappFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtWhatsappFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWhatsappFinanciamentoKeyPressed(evt);
            }
        });

        jLabel26.setText("Whatsapp:");

        try {
            txtTelefoneFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneFinanciamentoKeyPressed(evt);
            }
        });

        txtCPFFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFinanciamentoFocusLost(evt);
            }
        });
        txtCPFFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFFinanciamentoKeyPressed(evt);
            }
        });

        jLabel28.setText("COMPL:");

        txtComplementoFinanciamento.setPreferredSize(new java.awt.Dimension(90, 22));
        txtComplementoFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoFinanciamentoActionPerformed(evt);
            }
        });
        txtComplementoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComplementoFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComplementoFinanciamentoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeFinanciamento)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtCEPFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnderecoFinanciamento)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtBairroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtComplementoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(txtWhatsappFinanciamento))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbCidadeFinanciamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbUFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtCEPFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(txtComplementoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBairroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbCidadeFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtWhatsappFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(243, 245, 251));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Financiamento"));

        jLabel10.setText("DATA:");

        dtFinanciamento.setDateFormatString("dd'-'MM'-'yyyy");
        dtFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dtFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel11.setText("QTD. PARCELAS:");

        cbQtdParcelasFinanciamento.setEditable(true);
        cbQtdParcelasFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "6", "10", "12", "18", "24", "30", "36", "42", "48", "50", "60", "72", " " }));
        cbQtdParcelasFinanciamento.setEnabled(false);

        jLabel12.setText("VALOR PARCELA:");

        jLabel15.setText("DIA DE VENCIMENTO: ");

        cbDiaVencimentoFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        txtValParcelaFinanciamento.setEditable(false);
        txtValParcelaFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValParcelaFinanciamento.setText("0,00");
        txtValParcelaFinanciamento.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValParcelaFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValParcelaFinanciamentoKeyPressed(evt);
            }
        });

        txtObsFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObsFinanciamentoKeyPressed(evt);
            }
        });

        jLabel24.setText("OBS:");

        txtFicha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtFicha.setEnabled(false);
        txtFicha.setMaximumSize(new java.awt.Dimension(64, 22));
        txtFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFichaKeyPressed(evt);
            }
        });

        jLabel27.setText("Ficha");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtObsFinanciamento))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbDiaVencimentoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtFinanciamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(cbDiaVencimentoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObsFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFinanciamentoActionPerformed
     if( this.financiamento !=null){         
         
         //atualiza o financiamento
         //this.financiamento.setDia_vencimento(Integer.valueOf(this.cbDiaVencimentoFinanciamento.getSelectedItem().toString()));
         this.financiamento.setFicha(!"".equals(this.txtFicha.getText())?Integer.valueOf(this.txtFicha.getText()):null);
         this.financiamento.setOberservacao(!"".equals(this.txtObsFinanciamento.getText())?this.txtObsFinanciamento.getText(): null);
         this.financiamento.setValor_parcela(Double.valueOf(this.txtValParcelaFinanciamento.getText().replace(",", ".")));
         //valores da entrada
         this.financiamento.getCliente().setNome(!"".equals(this.txtNomeFinanciamento.getText())?this.txtNomeFinanciamento.getText():null);
         this.financiamento.getCliente().setBairro(!"".equals(this.txtBairroFinanciamento.getText())?this.txtBairroFinanciamento.getText():null);
         this.financiamento.getCliente().setCep(!"".equals(this.txtCEPFinanciamento.getText())?this.txtCEPFinanciamento.getText():null);
         this.financiamento.getCliente().setCpf(!"".equals(this.txtCPFFinanciamento.getText())?this.txtCPFFinanciamento.getText():null);
         this.financiamento.getCliente().setEndereco(!"".equals(this.txtEnderecoFinanciamento.getText())?this.txtEnderecoFinanciamento.getText():null);
         this.financiamento.getCliente().setNumero("".equals(this.txtNumeroFinanciamento.getText())? null : Integer.valueOf(this.txtNumeroFinanciamento.getText()));
         this.financiamento.getCliente().setRg(!"".equals(this.txtRgFinanciamento.getText())?this.txtRgFinanciamento.getText(): null);
         this.financiamento.getCliente().setTelefone(!"".equals(this.txtTelefoneFinanciamento.getText())?this.txtTelefoneFinanciamento.getText():null);
         this.financiamento.getCliente().setWhatsapp(!"".equals(this.txtWhatsappFinanciamento.getText())?this.txtWhatsappFinanciamento.getText():null);
         this.financiamento.getCliente().setComplemento(!"".equals(this.txtComplementoFinanciamento.getText())?this.txtComplementoFinanciamento.getText():null);
         try{
             int id_Estado = EstadoDB.searchIdStateByName(this.cbUFFinanciamento.getSelectedItem().toString());
             this.financiamento.getCliente().setId_municipio(MunicipioDB.searchIdByCidade(this.cbCidadeFinanciamento.getSelectedItem().toString(), id_Estado));
    
             if( !"".equals(this.cbDiaVencimentoFinanciamento.getSelectedItem().toString()) && !Objects.equals(Integer.valueOf(this.cbDiaVencimentoFinanciamento.getSelectedItem().toString()), this.financiamento.getDia_vencimento()) ){
                 //atualiza parcelas
                 
                 int intervaloDias = this.financiamento.getDia_vencimento() - Integer.valueOf(this.cbDiaVencimentoFinanciamento.getSelectedItem().toString());
                  ParcelamentoDB.atualizaDiaVencimento(intervaloDias, this.financiamento.getId());                 
                 this.financiamento.setDia_vencimento(Integer.valueOf(this.cbDiaVencimentoFinanciamento.getSelectedItem().toString()));                 
             }
             FinanciamentoDB.update(this.financiamento, this.financiamento.getCliente());
             JOptionPane.showMessageDialog(null, "Registro atualizado!","Update", JOptionPane.INFORMATION_MESSAGE);
         }catch(NullPointerException e){
             JOptionPane.showMessageDialog(rootPane, "Falha ao acesso o banco de dados!", null, JOptionPane.ERROR_MESSAGE);
         }
         
         
     } 
    }//GEN-LAST:event_btnSalvarFinanciamentoActionPerformed

    private void btnImprimirFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirFinanciamentoActionPerformed
      if( this.entrada != null ){ 
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(new PrintingFichaFrenteFinanciamento(this.financiamento));
            boolean doPrint = job.printDialog();
                if (doPrint) 
                    try {
                        job.print();
                    } catch (PrinterException ex) {
                        Logger.getLogger(FormNovoFinanciamento.class.getName()).log(Level.SEVERE, null, ex);
                    }
            
            int imprimirFichaVerso = JOptionPane.showConfirmDialog(rootPane, "Deja impirmir o verso da ficha?");
            if( imprimirFichaVerso == 0  ){
                job = PrinterJob.getPrinterJob();
                job.setPrintable(new PrintingFichaVersoFinanciamento(this.financiamento));
                doPrint = job.printDialog();
                    if (doPrint) 
                        try {
                            job.print();
                        } catch (PrinterException ex) {
                             Logger.getLogger(FormNovoFinanciamento.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }    
       }
    }//GEN-LAST:event_btnImprimirFinanciamentoActionPerformed

    private void btnExcluirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEntradaActionPerformed

    private void btnLimparFormularioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparFormularioEntradaActionPerformed

    private void txtPesquisarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarFinanciamentoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        Financiamento.janelaEditarFinanciamento = true;
        System.out.println(Financiamento.janelaEditarFinanciamento);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtPesquisarFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoMouseClicked
        //recuperando os dados do formulario
        
        
        
        
    }//GEN-LAST:event_txtPesquisarFinanciamentoMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        Financiamento.janelaEditarFinanciamento = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        Financiamento.janelaEditarFinanciamento = true;
    
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
        Financiamento.janelaEditarFinanciamento = false;
   
    }//GEN-LAST:event_formAncestorRemoved

    private void btnLimparFormularioEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnLimparFormularioEntradaMouseClicked

    private void txtPesquisarFinanciamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPesquisarFinanciamentoMouseReleased

    private void btnPesquisarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoActionPerformed
    
            //pequisar pelo numero da ficha(int)           
            if( this.txtPesquisarFinanciamento.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Digite o numero da ficha no campo de pesquisa!");
                return;
            }            
            boolean testeCampoPesquisa = false;
            testeCampoPesquisa = Validacao.isNumber(this.txtPesquisarFinanciamento.getText());
            if( testeCampoPesquisa == false ) {
                JOptionPane.showMessageDialog(this, "Digite apenas números!");
                return;
            }
            
            try{
                if( "Ficha".equals(this.cbOptionPesquisa.getSelectedItem().toString())){
                   this.financiamento = FinanciamentoDB.buscaFinanciamentoPorNFicha(Integer.parseInt(this.txtPesquisarFinanciamento.getText()));
                    if( this.financiamento == null ) throw new DaoException("Nenhum financiamento encontrado ou falha ao acessar o banco de dados");

                    //preenche formulario entrada           
                    this.txtMarcaEntrada.setText(this.financiamento.getVeiculo().getMarca());
                    this.txtModeloEntrada.setText(this.financiamento.getVeiculo().getModelo());
                    this.txtRenavamEntrada.setText(this.financiamento.getVeiculo().getRenavam());
                    this.txtChassiEntrada.setText(this.financiamento.getVeiculo().getChassi());
                    this.txtPlacaEntrada.setText(this.financiamento.getVeiculo().getPlaca());
                    this.cbAnoEntrada.setSelectedItem(this.financiamento.getVeiculo().getAno());
                    this.cbCorEntrada.setSelectedItem(this.financiamento.getVeiculo().getCor());
                    //fim formulario entrada
                    //preenche formulario cliente
                    this.txtNomeFinanciamento.setText(this.financiamento.getCliente().getNome());
                    this.txtRgFinanciamento.setText(this.financiamento.getCliente().getRg());
                    this.txtCPFFinanciamento.setText(this.financiamento.getCliente().getCpf());
                    this.txtCEPFinanciamento.setText(this.financiamento.getCliente().getCep());
                    this.txtEnderecoFinanciamento.setText(this.financiamento.getCliente().getEndereco());
                    this.txtBairroFinanciamento.setText(this.financiamento.getCliente().getBairro());
                    this.txtNumeroFinanciamento.setText(String.valueOf(this.financiamento.getCliente().getNumero()));                          
                        Municipio municipio;                     
                        municipio = MunicipioDB.buscaCidadePorId(this.financiamento.getCliente().getId_municipio());
                        if( municipio != null ){
                            this.cbCidadeFinanciamento.setSelectedItem(municipio.getNome());
                            Estado estado;                        
                            estado = EstadoDB.searchById(municipio.getId_uf());
                            this.cbUFFinanciamento.setSelectedItem(estado.getNome()); 
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Falha ao acessar banco de dados!");
                        }
                    this.txtWhatsappFinanciamento.setText(this.financiamento.getCliente().getWhatsapp());
                    this.txtTelefoneFinanciamento.setText(this.financiamento.getCliente().getTelefone()); 
                    this.txtComplementoFinanciamento.setText(this.financiamento.getCliente().getComplemento());
                    //fim formulario cliente]
                    //preenche formulário financiamento
                    this.txtFicha.setText(String.valueOf(this.financiamento.getFicha()));
                    this.dtFinanciamento.setDate(this.financiamento.getData_registro());
                    this.txtValParcelaFinanciamento.setText(String.valueOf(this.financiamento.getValor_parcela()));
                    this.cbQtdParcelasFinanciamento.setSelectedItem(this.financiamento.getNum_parcelas());                
                    this.cbDiaVencimentoFinanciamento.setSelectedItem(this.financiamento.getDia_vencimento());
                    this.txtObsFinanciamento.setText(this.financiamento.getOberservacao());
                    //fim formulario financiamento
                }
            }
            catch(DaoException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
                            
                            
                       
            
        
       
    }//GEN-LAST:event_btnPesquisarFinanciamentoActionPerformed

    private void txtPesquisarFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtPesquisarFinanciamento.setText(this.txtPesquisarFinanciamento.getText().toUpperCase());
    }//GEN-LAST:event_txtPesquisarFinanciamentoKeyReleased

    private void cbAnoEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbAnoEntradaAncestorAdded
        // TODO add your handling code here:
        for (int i = 1950; i < 2061; i++) {
            this.cbAnoEntrada.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_cbAnoEntradaAncestorAdded

    private void cbCorEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCorEntradaKeyTyped

    private void txtNomeFinanciamentoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoCaretUpdate

    private void txtNomeFinanciamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoFocusGained

    private void txtNomeFinanciamentoComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoComponentMoved

    private void txtNomeFinanciamentoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoCaretPositionChanged

    private void txtNomeFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtNomeFinanciamento.getText().length() > 99 ){
            this.txtNomeFinanciamento.setText( this.txtNomeFinanciamento.getText().substring(0, 99));
        }
    }//GEN-LAST:event_txtNomeFinanciamentoKeyPressed

    private void txtNomeFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtNomeFinanciamento.setText(Validacao.textoSemAcentuacaoEallUpperCase(this.txtNomeFinanciamento.getText(), "ÀÈÌÒÙÁÉÍÓÚÂÊÎÔÛÃÕÇ"));
    }//GEN-LAST:event_txtNomeFinanciamentoKeyReleased

    private void txtNomeFinanciamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoKeyTyped

    private void txtCEPFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPFinanciamentoActionPerformed

    private void txtCEPFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoKeyPressed
        // TODO add your handling code here:

        if( !Character.isDigit(evt.getKeyChar())){
            if( this.txtCEPFinanciamento.getText().length() > 0){
                this.txtCEPFinanciamento.setText(this.txtCEPFinanciamento.getText().substring(0, this.txtCEPFinanciamento.getText().length()-1));
                this.txtCEPFinanciamento.setToolTipText("Digite apenas números");
            }
        }else{
            int  letraLen = this.txtCEPFinanciamento.getText().length();
            if( letraLen == 5){
                this.txtCEPFinanciamento.setText(this.txtCEPFinanciamento.getText() + "-");
            }

            if(letraLen > 8 ){
                this.txtCEPFinanciamento.setText(this.txtCEPFinanciamento.getText().substring(0, 8));
            }

        }
    }//GEN-LAST:event_txtCEPFinanciamentoKeyPressed

    private void txtCEPFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPFinanciamentoKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCEPFinanciamentoKeyReleased

    private void txtEnderecoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtEnderecoFinanciamento.getText().length() > 99 ){
            this.txtEnderecoFinanciamento.setText( this.txtEnderecoFinanciamento.getText().substring(0, 99));
        }
    }//GEN-LAST:event_txtEnderecoFinanciamentoKeyPressed

    private void txtEnderecoFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtEnderecoFinanciamento.setText(Validacao.textoSemAcentuacaoEallUpperCase(this.txtEnderecoFinanciamento.getText(), "ÀÈÌÒÙÁÉÍÓÚÂÊÎÔÛÃÕÇ"));
    }//GEN-LAST:event_txtEnderecoFinanciamentoKeyReleased

    private void txtBairroFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtBairroFinanciamento.getText().length() > 99 ){
            this.txtBairroFinanciamento.setText( this.txtBairroFinanciamento.getText().substring(0, 99));
        }
    }//GEN-LAST:event_txtBairroFinanciamentoKeyPressed

    private void txtBairroFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtBairroFinanciamento.setText(Validacao.textoSemAcentuacaoEallUpperCase(this.txtBairroFinanciamento.getText(), "ÀÈÌÒÙÁÉÍÓÚÂÊÎÔÛÃÕÇ"));
    }//GEN-LAST:event_txtBairroFinanciamentoKeyReleased

    private void txtNumeroFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFinanciamentoKeyReleased
        // TODO add your handling code here:

        if( !Character.isDigit(evt.getKeyChar())){
            if( this.txtNumeroFinanciamento.getText().length() > 0){
                this.txtNumeroFinanciamento.setText(this.txtNumeroFinanciamento.getText().substring(0, this.txtNumeroFinanciamento.getText().length()-1));
                this.txtNumeroFinanciamento.setToolTipText("Digite apenas números");
                JOptionPane.showMessageDialog(this, "Digite apenas números", "Error", JOptionPane.WARNING_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_txtNumeroFinanciamentoKeyReleased

    private void cbCidadeFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCidadeFinanciamentoAncestorAdded
        // TODO add your handling code here:
        List<Municipio> municipios;

        municipios = MunicipioDB.selectAllByState("São Paulo");
        for(Municipio municipio: municipios){
            this.cbCidadeFinanciamento.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbCidadeFinanciamentoAncestorAdded

    private void cbUFFinanciamentoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoComponentAdded
        // TODO add your handling code here:
        List<Municipio> municipios;
        municipios = MunicipioDB.selectAllByState(cbUFFinanciamento.getSelectedItem().toString());
        this.cbCidadeFinanciamento.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeFinanciamento.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFFinanciamentoComponentAdded

    private void cbUFFinanciamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoItemStateChanged
        // TODO add your handling code here:
        List<Municipio> municipios;
        municipios = MunicipioDB.selectAllByState(cbUFFinanciamento.getSelectedItem().toString());
        this.cbCidadeFinanciamento.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeFinanciamento.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFFinanciamentoItemStateChanged

    private void cbUFFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbUFFinanciamentoAncestorAdded
        // TODO add your handling code here:
        List<Estado> estados;

        estados = EstadoDB.selectAll();

        for(Estado estado: estados){
            this.cbUFFinanciamento.addItem(estado.getNome());
        }
    }//GEN-LAST:event_cbUFFinanciamentoAncestorAdded

    private void txtRgFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRgFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtRgFinanciamento.getText().length() > 12 ){
            this.txtRgFinanciamento.setText( this.txtRgFinanciamento.getText().substring(0, 12));
        }
    }//GEN-LAST:event_txtRgFinanciamentoKeyPressed

    private void txtWhatsappFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhatsappFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtWhatsappFinanciamento.getText().length() > 15 ){
            this.txtWhatsappFinanciamento.setText( this.txtWhatsappFinanciamento.getText().substring(0, 15));
        }
    }//GEN-LAST:event_txtWhatsappFinanciamentoKeyPressed

    private void txtTelefoneFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtTelefoneFinanciamento.getText().length() > 15 ){
            this.txtTelefoneFinanciamento.setText( this.txtTelefoneFinanciamento.getText().substring(0, 15));
        }
    }//GEN-LAST:event_txtTelefoneFinanciamentoKeyPressed

    private void txtCPFFinanciamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoFocusLost
        // TODO add your handling code here:
        if( this.txtCPFFinanciamento.getText().length() < 11 && !this.txtCPFFinanciamento.getText().isBlank() ){
            JOptionPane.showMessageDialog(this, "CPF inválido");
            this.txtCPFFinanciamento.requestFocus();

        }else if(!this.txtCPFFinanciamento.getText().isBlank()&& this.txtCPFFinanciamento.getText().length() == 11 ){
            if( Validacao.validaCPF(this.txtCPFFinanciamento.getText()) == false ){
                JOptionPane.showMessageDialog(this, "CPF inválido");
                this.txtCPFFinanciamento.requestFocus();
                this.txtCPFFinanciamento.setText("");
            }
        }

    }//GEN-LAST:event_txtCPFFinanciamentoFocusLost

    private void txtCPFFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtCPFFinanciamento.getText().length() > 10 ){
            this.txtCPFFinanciamento.setText( this.txtCPFFinanciamento.getText().substring(0, 10));
        }
    }//GEN-LAST:event_txtCPFFinanciamentoKeyPressed

    private void dtFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dtFinanciamentoAncestorAdded
        // TODO add your handling code here:
        java.util.Date data = new java.util.Date();
        this.dtFinanciamento.setDate(data);
    }//GEN-LAST:event_dtFinanciamentoAncestorAdded

    private void txtValParcelaFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValParcelaFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtValParcelaFinanciamento.getText().length() > 11 ){
            this.txtValParcelaFinanciamento.setText( this.txtValParcelaFinanciamento.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtValParcelaFinanciamentoKeyPressed

    private void txtObsFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsFinanciamentoKeyPressed
        // TODO add your handling code here:
        if( this.txtObsFinanciamento.getText().length() > 199 ){
            this.txtObsFinanciamento.setText( this.txtObsFinanciamento.getText().substring(0, 199));
        }
    }//GEN-LAST:event_txtObsFinanciamentoKeyPressed

    private void txtFichaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFichaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFichaKeyPressed

    private void txtComplementoFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoFinanciamentoActionPerformed

    private void txtComplementoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoFinanciamentoKeyPressed

    private void txtComplementoFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoFinanciamentoKeyReleased
        this.txtComplementoFinanciamento.setText(this.txtComplementoFinanciamento.getText().toUpperCase());
    }//GEN-LAST:event_txtComplementoFinanciamentoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirEntrada;
    private javax.swing.JButton btnImprimirFinanciamento;
    private javax.swing.JButton btnLimparFormularioEntrada;
    private javax.swing.JButton btnPesquisarFinanciamento;
    private javax.swing.JButton btnSalvarFinanciamento;
    private javax.swing.JComboBox<String> cbAnoEntrada;
    private javax.swing.JComboBox<String> cbCidadeFinanciamento;
    private javax.swing.JComboBox<String> cbCorEntrada;
    private javax.swing.JComboBox<String> cbDiaVencimentoFinanciamento;
    private javax.swing.JComboBox<String> cbOptionPesquisa;
    private javax.swing.JComboBox<String> cbQtdParcelasFinanciamento;
    private javax.swing.JComboBox<String> cbUFFinanciamento;
    private com.toedter.calendar.JDateChooser dtFinanciamento;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtBairroFinanciamento;
    private javax.swing.JTextField txtCEPFinanciamento;
    private javax.swing.JTextField txtCPFFinanciamento;
    private javax.swing.JTextField txtChassiEntrada;
    private javax.swing.JTextField txtComplementoFinanciamento;
    private javax.swing.JTextField txtEnderecoFinanciamento;
    private javax.swing.JFormattedTextField txtFicha;
    private javax.swing.JTextField txtMarcaEntrada;
    private javax.swing.JTextField txtModeloEntrada;
    private javax.swing.JTextField txtNomeFinanciamento;
    private javax.swing.JTextField txtNumeroFinanciamento;
    private javax.swing.JTextField txtObsFinanciamento;
    private javax.swing.JTextField txtPesquisarFinanciamento;
    private javax.swing.JTextField txtPlacaEntrada;
    private javax.swing.JTextField txtRenavamEntrada;
    private javax.swing.JFormattedTextField txtRgFinanciamento;
    private javax.swing.JFormattedTextField txtTelefoneFinanciamento;
    private javax.swing.JFormattedTextField txtValParcelaFinanciamento;
    private javax.swing.JFormattedTextField txtWhatsappFinanciamento;
    // End of variables declaration//GEN-END:variables
}
