/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.wesleycoelho.view;

import com.mongodb.client.model.Filters;
import com.wesleycoelho.controllers.jdbc.conn.ConnectionFactory;
import com.wesleycoelho.controllers.jdbc.conn.EntradaVeiculoDB;
import com.wesleycoelho.controllers.jdbc.conn.EstadoDB;
import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Usuario;
import javax.swing.JOptionPane;
import com.wesleycoelho.model.Estado;
import com.wesleycoelho.model.PrintingEntradaVeiculo;
import java.awt.Cursor;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;
import mongoDB.CrudMongoDB;
import org.bson.Document;



/**
 *
 * @author Wesley
 */
public class FormListarTodasEntradas extends javax.swing.JInternalFrame {
    private Usuario usuario = new Usuario();
    private List<EntradaVeiculo> listaEntradas = new ArrayList<>();
    private List<Document>       listaEntradasDoc = new ArrayList<>();;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form FormNovaEntrada
     */
    public FormListarTodasEntradas(Usuario user) {
        this.usuario = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSalvarEntrada = new javax.swing.JButton();
        btnImprimirEntrada = new javax.swing.JButton();
        btnExcluirEntrada = new javax.swing.JButton();
        btnLimparFormularioEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnFiltrarEntrada = new javax.swing.JButton();
        cbFiltroLista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEntradasVeiculo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TODOS os veículos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-car-16_1.png"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSalvarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-16.png"))); // NOI18N
        btnSalvarEntrada.setToolTipText("Salvar");
        btnSalvarEntrada.setEnabled(false);
        btnSalvarEntrada.setFocusable(false);
        btnSalvarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvarEntrada);

        btnImprimirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-print-16.png"))); // NOI18N
        btnImprimirEntrada.setToolTipText("Imprimir");
        btnImprimirEntrada.setFocusable(false);
        btnImprimirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirEntrada);

        btnExcluirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-trash-16.png"))); // NOI18N
        btnExcluirEntrada.setToolTipText("Excluir");
        btnExcluirEntrada.setEnabled(false);
        btnExcluirEntrada.setFocusable(false);
        btnExcluirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirEntrada);

        btnLimparFormularioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-broom-16.png"))); // NOI18N
        btnLimparFormularioEntrada.setToolTipText("Limpar Formulário");
        btnLimparFormularioEntrada.setEnabled(false);
        btnLimparFormularioEntrada.setFocusable(false);
        btnLimparFormularioEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFormularioEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFormularioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparFormularioEntradaMouseClicked(evt);
            }
        });
        btnLimparFormularioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormularioEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimparFormularioEntrada);
        jToolBar1.add(jSeparator1);

        btnFiltrarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-filter-16.png"))); // NOI18N
        btnFiltrarEntrada.setFocusable(false);
        btnFiltrarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiltrarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFiltrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFiltrarEntrada);

        cbFiltroLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Disponiveis", " " }));
        cbFiltroLista.setMaximumSize(new java.awt.Dimension(150, 20));
        jToolBar1.add(cbFiltroLista);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        tbEntradasVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data de entrada", "Proprietario", "Placa", "Marca", "Modelo", "Cor", "Ano", "Renavam", "Chassi", "Cidade", "Telefone", "Whatsapp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEntradasVeiculo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbEntradasVeiculo.setDoubleBuffered(true);
        tbEntradasVeiculo.setInheritsPopupMenu(true);
        tbEntradasVeiculo.setOpaque(false);
        tbEntradasVeiculo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbEntradasVeiculo.setShowGrid(true);
        tbEntradasVeiculo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbEntradasVeiculoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbEntradasVeiculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEntradaActionPerformed
        // TODO add your handling code here: 
        
        String nomeMunicipio = "";
        String nome_Uf = "";
        
        int id_Uf = 0;
        EntradaVeiculo entradaVeiculo = new EntradaVeiculo();
        
        List<Estado> estados = EstadoDB.searchByName(nome_Uf);
                id_Uf = estados.getFirst().getId();              
                String sql = "SELECT * FROM municipio WHERE nome = '"+nomeMunicipio+"' AND id_uf = "+id_Uf+";";
                 Connection conn = ConnectionFactory.getConexao();         
                try {            
                    Statement stmt = conn.createStatement();
                    ResultSet resultSet = stmt.executeQuery(sql);            
                    while(resultSet.next()){               
                       entradaVeiculo.setId_municipio(resultSet.getInt("id"));
                       
                        }
                    ConnectionFactory.close(conn, stmt, resultSet);          
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Erro: \nEstado e cidade não correspondem. \nOperação cancelada!");
                    Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
                }              
     
        
        entradaVeiculo.setUsuario(this.usuario.getUsuario());       
        JOptionPane.showMessageDialog(this,entradaVeiculo.getData_entrada());
         JOptionPane.showMessageDialog(this,entradaVeiculo.getId_municipio());
        EntradaVeiculoDB.save(entradaVeiculo);
        JOptionPane.showMessageDialog(this, "Nova entrada de veículo cadastrada com sucesso!");
        
        
        
        
    }//GEN-LAST:event_btnSalvarEntradaActionPerformed

    private void btnImprimirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEntradaActionPerformed
        try {
            EntradaVeiculo entrada = this.listaEntradas.get(this.tbEntradasVeiculo.getSelectedRow());         
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(new PrintingEntradaVeiculo(entrada));
            boolean doPrint = job.printDialog();
            if (doPrint) job.print();
        } catch (PrinterException e ) {
            JOptionPane.showMessageDialog(null, "Falha ao imprimir");
        }catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Selecione 1 item da lista");
        }
    }//GEN-LAST:event_btnImprimirEntradaActionPerformed

    private void btnExcluirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEntradaActionPerformed

    private void btnLimparFormularioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparFormularioEntradaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        EntradaVeiculo.janelaListarEntrada = true;
        System.out.println(EntradaVeiculo.janelaListarEntrada);
       
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        EntradaVeiculo.janelaListarEntrada = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        EntradaVeiculo.janelaListarEntrada = true;
    
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
        EntradaVeiculo.janelaListarEntrada = false;
   
    }//GEN-LAST:event_formAncestorRemoved

    private void btnLimparFormularioEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLimparFormularioEntradaMouseClicked

    private void btnFiltrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarEntradaActionPerformed
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(this.cbFiltroLista.getSelectedItem().toString() == "Todos"){
            
            //this.listaEntradas = EntradaVeiculoDB.selectAll();
            this.listaEntradasDoc = CrudMongoDB.searchAll("entrada_veiculo");
            for(Document d : listaEntradasDoc ){
                EntradaVeiculo e = new EntradaVeiculo();
                e.convertToJavaObj(d);
                this.listaEntradas.add(e);
            }
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel = (DefaultTableModel) this.tbEntradasVeiculo.getModel();
            tableModel.setNumRows(0);
            for(Document entrada: listaEntradasDoc ){
                Object[] colunas = new Object[12];
              
                colunas[0] = entrada.getDate("data_entrada") == null ? null : sdf.format(entrada.getDate("data_entrada"));
                colunas[1] = entrada.getString("nome_proprietario");
                colunas[2] = entrada.getString("placa");
                colunas[3] = entrada.getString("marca");
                colunas[4] = entrada.getString("modelo");
                colunas[5] = entrada.getString("cor");
                colunas[6] = entrada.getString("ano_veiculo");
                colunas[7] = entrada.getString("renavam");
                colunas[8] = entrada.getString("chassi");
                colunas[9] = entrada.getInteger("id_municipio") == null ? null : CrudMongoDB.searchByFieldValue("cidades", "id", entrada.getInteger("id_municipio")).getString("name");
                colunas[10] = entrada.getString("telefone");
                colunas[11] = entrada.getString("whatsapp");
                
                
                tableModel.addRow(colunas);
            }
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        
        if(this.cbFiltroLista.getSelectedItem().toString() == "Disponiveis"){            
            this.listaEntradasDoc = CrudMongoDB.searchAll("entrada_veiculo");
            List<Document> saidas = CrudMongoDB.searchAll("saida_veiculo");
            for( Document doc: saidas ){
                List<Document> result = this.listaEntradasDoc.stream().filter(x -> x.getObjectId("_id").compareTo(doc.getObjectId("_id_entrada")) == 0 ).collect(Collectors.toList());
                this.listaEntradasDoc.removeAll(result);
            }
            //listaEntradas = EntradaVeiculoDB.selectAllAvaliable(); 
            for(Document d : listaEntradasDoc ){
                EntradaVeiculo e = new EntradaVeiculo();
                e.convertToJavaObj(d);
                this.listaEntradas.add(e);
            }
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel = (DefaultTableModel) this.tbEntradasVeiculo.getModel();
            tableModel.setNumRows(0);
            for(Document entrada:  this.listaEntradasDoc ){ 
                Object[] colunas = new Object[12];
                colunas[0] = entrada.getDate("data_entrada") == null ? null :sdf.format(entrada.getDate("data_entrada"));
                colunas[1] = entrada.getString("nome_proprietario");
                colunas[2] = entrada.getString("placa");
                colunas[3] = entrada.getString("marca");
                colunas[4] = entrada.getString("modelo");
                colunas[5] = entrada.getString("cor");
                colunas[6] = entrada.getString("ano_veiculo");
                colunas[7] = entrada.getString("renavam");
                colunas[8] = entrada.getString("chassi");
                colunas[9] = entrada.getInteger("id_municipio") == null ? null : CrudMongoDB.searchByFieldValue("cidades", "id", entrada.getInteger("id_municipio")).getString("name");
                colunas[10] = entrada.getString("telefone");
                colunas[11] = entrada.getString("whatsapp");
                tableModel.addRow(colunas);
            }
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnFiltrarEntradaActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_formComponentAdded

    private void tbEntradasVeiculoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbEntradasVeiculoAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_tbEntradasVeiculoAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirEntrada;
    private javax.swing.JButton btnFiltrarEntrada;
    private javax.swing.JButton btnImprimirEntrada;
    private javax.swing.JButton btnLimparFormularioEntrada;
    private javax.swing.JButton btnSalvarEntrada;
    private javax.swing.JComboBox<String> cbFiltroLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbEntradasVeiculo;
    // End of variables declaration//GEN-END:variables
}
