/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wesleycoelho.view;

import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Financiamento;
import com.wesleycoelho.model.Parcelamento;
import com.wesleycoelho.model.Inadimplente;
import com.wesleycoelho.model.SaidaVeiculo;
import com.wesleycoelho.model.Usuario;
import java.awt.Color;
import java.awt.Cursor;



import javax.swing.ImageIcon;

/**
 *
 * @author Wesley
 */
public class FormDesktop extends javax.swing.JFrame {
    
    Usuario usuario = new Usuario();
     Color corBotaoMenuAtivado = new Color(45,50,80);
     Color corBotaoMenuInativo = new Color(0,102,204);
     Color corBotaoSubMenuAtivado = new Color(63,69,104);
     Color corBotaoSubMenuDesativado = new Color(45,50,80);
     Color corBotaoSubMenuPressed = new Color(71,77,113);
     Color corBotaoSubMenuReleased = new Color(63,69,104);
    /**
     * Creates new form FormDesktop
     * @param user
     */
    public FormDesktop(Usuario user) {
        this.usuario = user;
        initComponents();        
        ImageIcon icone = new ImageIcon(getClass().getResource("/Icon 20 x 20.png"));
        this.setIconImage(icone.getImage());
    }
    public FormDesktop() {
           this.pnlPopupMenuEntrada.setVisible(false);
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        pnlLateral = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JLabel();
        btnFinanciamento = new javax.swing.JLabel();
        btnSaida = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JLabel();
        btnPagamento = new javax.swing.JLabel();
        txtIdentificaUsuario = new javax.swing.JLabel();
        txtLogout = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlPopupMenuEntrada = new javax.swing.JPanel();
        btnNovaEntrada = new javax.swing.JLabel();
        btnEditarEntrada = new javax.swing.JLabel();
        btnListarEntrada = new javax.swing.JLabel();
        btnPesquisarEntrada = new javax.swing.JLabel();
        pnlPopupMenuFinanciamento = new javax.swing.JPanel();
        btnNovoFinanciamento = new javax.swing.JLabel();
        btnEditarFinanciamento = new javax.swing.JLabel();
        btnListarFinanciamento = new javax.swing.JLabel();
        btnPesquisarFinanciamento = new javax.swing.JLabel();
        pnlPopupMenuSaida = new javax.swing.JPanel();
        btnNovaSaida = new javax.swing.JLabel();
        btnListarSaida = new javax.swing.JLabel();
        btnPesquisarSaida = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Interface Resources Analytics");

        Desktop.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                DesktopComponentAdded(evt);
            }
        });
        Desktop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesktopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        pnlLateral.setBackground(new java.awt.Color(0, 102, 204));
        pnlLateral.setMaximumSize(new java.awt.Dimension(206, 32767));
        pnlLateral.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlLateralAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnEntrada.setBackground(new java.awt.Color(0, 102, 204));
        btnEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-car-16.png"))); // NOI18N
        btnEntrada.setText("Entrada                               ");
        btnEntrada.setAlignmentX(10.0F);
        btnEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEntrada.setIconTextGap(10);
        btnEntrada.setInheritsPopupMenu(false);
        btnEntrada.setOpaque(true);
        btnEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnEntrada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEntradaMouseMoved(evt);
            }
        });
        btnEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntradaMouseExited(evt);
            }
        });

        btnFinanciamento.setBackground(new java.awt.Color(0, 102, 204));
        btnFinanciamento.setForeground(new java.awt.Color(255, 255, 255));
        btnFinanciamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-document-16.png"))); // NOI18N
        btnFinanciamento.setText("Financiamento                   ");
        btnFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFinanciamento.setIconTextGap(10);
        btnFinanciamento.setOpaque(true);
        btnFinanciamento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnFinanciamentoMouseMoved(evt);
            }
        });
        btnFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinanciamentoMouseClicked(evt);
            }
        });

        btnSaida.setBackground(new java.awt.Color(0, 102, 204));
        btnSaida.setForeground(new java.awt.Color(255, 255, 255));
        btnSaida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-car-16.png"))); // NOI18N
        btnSaida.setText("Saída                                  ");
        btnSaida.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSaida.setIconTextGap(10);
        btnSaida.setOpaque(true);
        btnSaida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSaidaMouseMoved(evt);
            }
        });
        btnSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaidaMouseClicked(evt);
            }
        });

        btnRelatorio.setBackground(new java.awt.Color(0, 102, 204));
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-graph-report-16.png"))); // NOI18N
        btnRelatorio.setText("Relatório                            ");
        btnRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRelatorio.setIconTextGap(10);
        btnRelatorio.setOpaque(true);
        btnRelatorio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseMoved(evt);
            }
        });
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseClicked(evt);
            }
        });

        btnPagamento.setBackground(new java.awt.Color(0, 102, 204));
        btnPagamento.setForeground(new java.awt.Color(255, 255, 255));
        btnPagamento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-us-dollar-circled-16.png"))); // NOI18N
        btnPagamento.setText("Pagamento                        ");
        btnPagamento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPagamento.setIconTextGap(10);
        btnPagamento.setOpaque(true);
        btnPagamento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPagamentoMouseMoved(evt);
            }
        });
        btnPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagamentoMouseEntered(evt);
            }
        });

        txtIdentificaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtIdentificaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtIdentificaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-16.png"))); // NOI18N
        txtIdentificaUsuario.setText("Olá, " + this.usuario.getUsuario() + "!");
        txtIdentificaUsuario.setToolTipText("");
        txtIdentificaUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        txtIdentificaUsuario.setIconTextGap(10);
        txtIdentificaUsuario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtIdentificaUsuarioComponentAdded(evt);
            }
        });

        txtLogout.setForeground(new java.awt.Color(255, 255, 255));
        txtLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-logout-16.png"))); // NOI18N
        txtLogout.setText(" Sair");
        txtLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtLogoutMouseMoved(evt);
            }
        });
        txtLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogoutMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 50 x 50.png"))); // NOI18N
        jLabel3.setText("  Java Interface Resources Analytics");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setIconTextGap(10);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        pnlPopupMenuEntrada.setBackground(new java.awt.Color(45, 50, 80));
        pnlPopupMenuEntrada.setInheritsPopupMenu(true);
        pnlPopupMenuEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlPopupMenuEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnNovaEntrada.setBackground(new java.awt.Color(45, 50, 80));
        btnNovaEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-16.png"))); // NOI18N
        btnNovaEntrada.setText("                  nova");
        btnNovaEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNovaEntrada.setIconTextGap(92);
        btnNovaEntrada.setOpaque(true);
        btnNovaEntrada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNovaEntradaMouseMoved(evt);
            }
        });
        btnNovaEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovaEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovaEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovaEntradaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNovaEntradaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNovaEntradaMouseReleased(evt);
            }
        });

        btnEditarEntrada.setBackground(new java.awt.Color(45, 50, 80));
        btnEditarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pencil-16.png"))); // NOI18N
        btnEditarEntrada.setText("                  editar");
        btnEditarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnEditarEntrada.setIconTextGap(85);
        btnEditarEntrada.setMaximumSize(new java.awt.Dimension(190, 18));
        btnEditarEntrada.setMinimumSize(new java.awt.Dimension(190, 18));
        btnEditarEntrada.setOpaque(true);
        btnEditarEntrada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarEntradaMouseMoved(evt);
            }
        });
        btnEditarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarEntradaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarEntradaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarEntradaMouseReleased(evt);
            }
        });

        btnListarEntrada.setBackground(new java.awt.Color(45, 50, 80));
        btnListarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnListarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-list-16.png"))); // NOI18N
        btnListarEntrada.setText("                  listar todas");
        btnListarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnListarEntrada.setIconTextGap(58);
        btnListarEntrada.setOpaque(true);
        btnListarEntrada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnListarEntradaMouseMoved(evt);
            }
        });
        btnListarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarEntradaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListarEntradaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnListarEntradaMouseReleased(evt);
            }
        });

        btnPesquisarEntrada.setBackground(new java.awt.Color(45, 50, 80));
        btnPesquisarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-searchWhite-16.png"))); // NOI18N
        btnPesquisarEntrada.setText("                  pesquisar");
        btnPesquisarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnPesquisarEntrada.setIconTextGap(67);
        btnPesquisarEntrada.setOpaque(true);
        btnPesquisarEntrada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPesquisarEntradaMouseMoved(evt);
            }
        });
        btnPesquisarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarEntradaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPesquisarEntradaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPesquisarEntradaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPopupMenuEntradaLayout = new javax.swing.GroupLayout(pnlPopupMenuEntrada);
        pnlPopupMenuEntrada.setLayout(pnlPopupMenuEntradaLayout);
        pnlPopupMenuEntradaLayout.setHorizontalGroup(
            pnlPopupMenuEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEditarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnListarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPesquisarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPopupMenuEntradaLayout.setVerticalGroup(
            pnlPopupMenuEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPopupMenuEntradaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNovaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEditarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnListarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPesquisarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnListarEntrada.getAccessibleContext().setAccessibleName("            listar todas");

        pnlPopupMenuFinanciamento.setBackground(new java.awt.Color(45, 50, 80));
        pnlPopupMenuFinanciamento.setInheritsPopupMenu(true);
        pnlPopupMenuFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlPopupMenuFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnNovoFinanciamento.setBackground(new java.awt.Color(45, 50, 80));
        btnNovoFinanciamento.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-16.png"))); // NOI18N
        btnNovoFinanciamento.setText("                  novo");
        btnNovoFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNovoFinanciamento.setIconTextGap(92);
        btnNovoFinanciamento.setOpaque(true);
        btnNovoFinanciamento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNovoFinanciamentoMouseMoved(evt);
            }
        });
        btnNovoFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoFinanciamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoFinanciamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoFinanciamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNovoFinanciamentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNovoFinanciamentoMouseReleased(evt);
            }
        });

        btnEditarFinanciamento.setBackground(new java.awt.Color(45, 50, 80));
        btnEditarFinanciamento.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pencil-16.png"))); // NOI18N
        btnEditarFinanciamento.setText("                  editar");
        btnEditarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnEditarFinanciamento.setIconTextGap(85);
        btnEditarFinanciamento.setOpaque(true);
        btnEditarFinanciamento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarFinanciamentoMouseMoved(evt);
            }
        });
        btnEditarFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarFinanciamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarFinanciamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarFinanciamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarFinanciamentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditarFinanciamentoMouseReleased(evt);
            }
        });

        btnListarFinanciamento.setBackground(new java.awt.Color(45, 50, 80));
        btnListarFinanciamento.setForeground(new java.awt.Color(255, 255, 255));
        btnListarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-list-16.png"))); // NOI18N
        btnListarFinanciamento.setText("                  listar todos");
        btnListarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnListarFinanciamento.setIconTextGap(58);
        btnListarFinanciamento.setOpaque(true);
        btnListarFinanciamento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnListarFinanciamentoMouseMoved(evt);
            }
        });
        btnListarFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarFinanciamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarFinanciamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarFinanciamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListarFinanciamentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnListarFinanciamentoMouseReleased(evt);
            }
        });

        btnPesquisarFinanciamento.setBackground(new java.awt.Color(45, 50, 80));
        btnPesquisarFinanciamento.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-searchWhite-16.png"))); // NOI18N
        btnPesquisarFinanciamento.setText("                  pesquisar");
        btnPesquisarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnPesquisarFinanciamento.setIconTextGap(67);
        btnPesquisarFinanciamento.setOpaque(true);
        btnPesquisarFinanciamento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPesquisarFinanciamentoMouseMoved(evt);
            }
        });
        btnPesquisarFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarFinanciamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarFinanciamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarFinanciamentoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPesquisarFinanciamentoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPesquisarFinanciamentoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPopupMenuFinanciamentoLayout = new javax.swing.GroupLayout(pnlPopupMenuFinanciamento);
        pnlPopupMenuFinanciamento.setLayout(pnlPopupMenuFinanciamentoLayout);
        pnlPopupMenuFinanciamentoLayout.setHorizontalGroup(
            pnlPopupMenuFinanciamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovoFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEditarFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnListarFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPesquisarFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPopupMenuFinanciamentoLayout.setVerticalGroup(
            pnlPopupMenuFinanciamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPopupMenuFinanciamentoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNovoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEditarFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnListarFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPesquisarFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlPopupMenuSaida.setBackground(new java.awt.Color(45, 50, 80));
        pnlPopupMenuSaida.setInheritsPopupMenu(true);
        pnlPopupMenuSaida.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlPopupMenuSaidaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnNovaSaida.setBackground(new java.awt.Color(45, 50, 80));
        btnNovaSaida.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-plus-16.png"))); // NOI18N
        btnNovaSaida.setText("                  nova");
        btnNovaSaida.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNovaSaida.setIconTextGap(92);
        btnNovaSaida.setOpaque(true);
        btnNovaSaida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNovaSaidaMouseMoved(evt);
            }
        });
        btnNovaSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovaSaidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovaSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovaSaidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNovaSaidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNovaSaidaMouseReleased(evt);
            }
        });

        btnListarSaida.setBackground(new java.awt.Color(45, 50, 80));
        btnListarSaida.setForeground(new java.awt.Color(255, 255, 255));
        btnListarSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-list-16.png"))); // NOI18N
        btnListarSaida.setText("                  listar todas");
        btnListarSaida.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnListarSaida.setIconTextGap(58);
        btnListarSaida.setOpaque(true);
        btnListarSaida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnListarSaidaMouseMoved(evt);
            }
        });
        btnListarSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarSaidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListarSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListarSaidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListarSaidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnListarSaidaMouseReleased(evt);
            }
        });

        btnPesquisarSaida.setBackground(new java.awt.Color(45, 50, 80));
        btnPesquisarSaida.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-searchWhite-16.png"))); // NOI18N
        btnPesquisarSaida.setText("                  pesquisar");
        btnPesquisarSaida.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnPesquisarSaida.setIconTextGap(67);
        btnPesquisarSaida.setOpaque(true);
        btnPesquisarSaida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPesquisarSaidaMouseMoved(evt);
            }
        });
        btnPesquisarSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarSaidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarSaidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPesquisarSaidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPesquisarSaidaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPopupMenuSaidaLayout = new javax.swing.GroupLayout(pnlPopupMenuSaida);
        pnlPopupMenuSaida.setLayout(pnlPopupMenuSaidaLayout);
        pnlPopupMenuSaidaLayout.setHorizontalGroup(
            pnlPopupMenuSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnListarSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPesquisarSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPopupMenuSaidaLayout.setVerticalGroup(
            pnlPopupMenuSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPopupMenuSaidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNovaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnListarSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPesquisarSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout pnlLateralLayout = new javax.swing.GroupLayout(pnlLateral);
        pnlLateral.setLayout(pnlLateralLayout);
        pnlLateralLayout.setHorizontalGroup(
            pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLateralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdentificaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(pnlPopupMenuEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPopupMenuFinanciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPopupMenuSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLateralLayout.setVerticalGroup(
            pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLateralLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPopupMenuEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPopupMenuFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPopupMenuSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdentificaUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogout)
                .addContainerGap())
        );

        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desktop)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Desktop))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntradaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradaMouseMoved
        // TODO add your handling code here:
        this.btnEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEntradaMouseMoved

    private void btnEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradaMouseExited
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_btnEntradaMouseExited

    private void btnEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradaMouseClicked
        // TODO add your handling code here:
          this.btnEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(!this.pnlPopupMenuEntrada.isVisible())
            this.pnlPopupMenuEntrada.setVisible(true);
        else
             this.pnlPopupMenuEntrada.setVisible(false);
        
        this.btnEntrada.setOpaque(true);
        this.btnEntrada.setBackground(corBotaoMenuAtivado);
        this.btnFinanciamento.setBackground(corBotaoMenuInativo);
        this.pnlPopupMenuFinanciamento.setVisible(false);
        this.pnlPopupMenuSaida.setVisible(false);
        this.btnSaida.setBackground(corBotaoMenuInativo);
        this.btnRelatorio.setBackground(corBotaoMenuInativo);
        this.btnPagamento.setBackground(corBotaoMenuInativo);
      
        this.btnFinanciamento.setOpaque(false);
        this.btnEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
  
        
    }//GEN-LAST:event_btnEntradaMouseClicked

    private void btnEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnEntradaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradaAncestorAdded

    private void btnFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinanciamentoMouseClicked
        // TODO add your handling code here:
        
        this.btnFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(!this.pnlPopupMenuFinanciamento.isVisible())
            this.pnlPopupMenuFinanciamento.setVisible(true);
        else
             this.pnlPopupMenuFinanciamento.setVisible(false);
        this.pnlPopupMenuEntrada.setVisible(false);
        this.pnlPopupMenuSaida.setVisible(false);
        this.btnEntrada.setOpaque(false);
        this.btnFinanciamento.setOpaque(true);
        this.btnEntrada.setBackground(corBotaoMenuInativo);
        this.btnFinanciamento.setBackground(corBotaoMenuAtivado);
        this.btnSaida.setBackground(corBotaoMenuInativo);
        this.btnRelatorio.setBackground(corBotaoMenuInativo);
        this.btnPagamento.setBackground(corBotaoMenuInativo);
        this.btnFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnFinanciamentoMouseClicked

    private void btnFinanciamentoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinanciamentoMouseMoved
        // TODO add your handling code here:
        this.btnFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnFinanciamentoMouseMoved

    private void btnSaidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaidaMouseMoved
        // TODO add your handling code here:
        this.btnSaida.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSaidaMouseMoved

    private void btnRelatorioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseMoved
        // TODO add your handling code here:
        this.btnRelatorio.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRelatorioMouseMoved

    private void btnPagamentoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagamentoMouseMoved
        // TODO add your handling code here:
        this.btnPagamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPagamentoMouseMoved

    private void btnSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaidaMouseClicked
        // TODO add your handling code here:
        this.btnSaida.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(!this.pnlPopupMenuSaida.isVisible())
            this.pnlPopupMenuSaida.setVisible(true);
        else
             this.pnlPopupMenuSaida.setVisible(false);
        this.btnSaida.setOpaque(true);
        this.btnFinanciamento.setOpaque(false);        
        this.btnEntrada.setOpaque(false);        
        this.pnlPopupMenuEntrada.setVisible(false);
        this.pnlPopupMenuFinanciamento.setVisible(false);
        this.btnEntrada.setBackground(corBotaoMenuInativo);
        this.btnFinanciamento.setBackground(corBotaoMenuInativo);
        this.btnSaida.setBackground(corBotaoMenuAtivado);
        this.btnRelatorio.setBackground(corBotaoMenuInativo);
        this.btnPagamento.setBackground(corBotaoMenuInativo);
         this.btnSaida.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
        //abrir internal frame
    }//GEN-LAST:event_btnSaidaMouseClicked

    private void btnRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseClicked
       this.btnRelatorio.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.lblStatus.setText("Abrindo janela Relatórios!");
        this.btnEntrada.setOpaque(false);
        this.btnPagamento.setOpaque(false);
        this.btnRelatorio.setOpaque(true);
        this.pnlPopupMenuEntrada.setVisible(false);
        this.pnlPopupMenuFinanciamento.setVisible(false);
        this.pnlPopupMenuSaida.setVisible(false);
        this.btnEntrada.setBackground(corBotaoMenuInativo);
        this.btnFinanciamento.setBackground(corBotaoMenuInativo);
        this.btnSaida.setBackground(corBotaoMenuInativo);
        this.btnRelatorio.setBackground(corBotaoMenuAtivado);
        this.btnPagamento.setBackground(corBotaoMenuInativo);
        
        //abrir internal frame

           FormRelatorio  frmRelatorio;
        if(Inadimplente.janelaRelatorio == false ){
            frmRelatorio = new FormRelatorio(this.usuario);
            this.Desktop.add(frmRelatorio);
            frmRelatorio.setVisible(true);
            frmRelatorio.toFront();
            frmRelatorio.requestFocus();
        }
        this.lblStatus.setText("Status: Pronto!");
        this.btnRelatorio.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRelatorioMouseClicked

    private void btnPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagamentoMouseClicked
        this.btnPagamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.btnEntrada.setOpaque(false);
        this.btnRelatorio.setOpaque(false);
        this.btnPagamento.setOpaque(true);
        this.pnlPopupMenuEntrada.setVisible(false);
        this.pnlPopupMenuFinanciamento.setVisible(false);
        this.pnlPopupMenuSaida.setVisible(false);
        this.btnEntrada.setBackground(corBotaoMenuInativo);
        this.btnFinanciamento.setBackground(corBotaoMenuInativo);
        this.btnSaida.setBackground(corBotaoMenuInativo);
        this.btnRelatorio.setBackground(corBotaoMenuInativo);
        this.btnPagamento.setBackground(corBotaoMenuAtivado);
        
        //abrir internal frame
           FormPagamento  frmPagamento;
        if(Parcelamento.janelaPagamento == false ){
            frmPagamento = new FormPagamento(this.usuario);
            this.Desktop.add(frmPagamento);
            frmPagamento.setVisible(true);
            frmPagamento.toFront();
            frmPagamento.requestFocus();
        }
        this.lblStatus.setText("Status: Pronto!");
        this.btnPagamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
    }//GEN-LAST:event_btnPagamentoMouseClicked

    private void txtIdentificaUsuarioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtIdentificaUsuarioComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdentificaUsuarioComponentAdded

    private void txtLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        FormLogin frmLogin = new FormLogin();
        frmLogin.setVisible(true);
    }//GEN-LAST:event_txtLogoutMouseClicked

    private void txtLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogoutMouseMoved
        // TODO add your handling code here:
         this.txtLogout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_txtLogoutMouseMoved

    private void pnlPopupMenuEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlPopupMenuEntradaAncestorAdded
        // TODO add your handling code here:
  
    }//GEN-LAST:event_pnlPopupMenuEntradaAncestorAdded

    private void DesktopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesktopMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_DesktopMouseClicked

    private void pnlLateralAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlLateralAncestorAdded
        // TODO add your handling code here:
        this.pnlPopupMenuEntrada.setVisible(false);
        this.pnlPopupMenuFinanciamento.setVisible(false);
        this.pnlPopupMenuSaida.setVisible(false);
    }//GEN-LAST:event_pnlLateralAncestorAdded

    private void btnNovaEntradaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaEntradaMouseMoved
        // TODO add your handling code here:
        this.btnNovaEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
      
    }//GEN-LAST:event_btnNovaEntradaMouseMoved

    private void btnEditarEntradaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEntradaMouseMoved
        // TODO add your handling code here:
        this.btnEditarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEditarEntradaMouseMoved

    private void btnListarEntradaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarEntradaMouseMoved
        // TODO add your handling code here:
        this.btnListarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnListarEntradaMouseMoved

    private void btnPesquisarEntradaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaMouseMoved
        // TODO add your handling code here:
        this.btnPesquisarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPesquisarEntradaMouseMoved

    private void btnNovaEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaEntradaMouseClicked
        this.btnNovaEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.lblStatus.setText("Status: abrindo formulário 'Nova Entrada de Veículo'");
        this.lblStatus.repaint();
        FormNovaEntrada frmNovaEntrada;
        //abrir internal frame
        
        if(EntradaVeiculo.janelaNovaEntrada == false ){
            frmNovaEntrada = new FormNovaEntrada(this.usuario);
            this.Desktop.add(frmNovaEntrada);
            frmNovaEntrada.setVisible(true);
            frmNovaEntrada.toFront();
            frmNovaEntrada.requestFocus();
        }
        this.lblStatus.setText("Status: Pronto!");
        this.lblStatus.repaint();
         this.btnNovaEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNovaEntradaMouseClicked

    private void btnNovaEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaEntradaMouseEntered
        // TODO add your handling code here:
          this.btnNovaEntrada.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnNovaEntradaMouseEntered

    private void btnNovaEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaEntradaMouseExited
        // TODO add your handling code here:
          this.btnNovaEntrada.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnNovaEntradaMouseExited

    private void btnEditarEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEntradaMouseEntered
        // TODO add your handling code here:
        this.btnEditarEntrada.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnEditarEntradaMouseEntered

    private void btnEditarEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEntradaMouseExited
        // TODO add your handling code here:
        this.btnEditarEntrada.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnEditarEntradaMouseExited

    private void btnListarEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarEntradaMouseExited
        // TODO add your handling code here:
         this.btnListarEntrada.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnListarEntradaMouseExited

    private void btnPesquisarEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaMouseExited
        // TODO add your handling code here:
         this.btnPesquisarEntrada.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnPesquisarEntradaMouseExited

    private void btnListarEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarEntradaMouseEntered
        // TODO add your handling code here:
        this.btnListarEntrada.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnListarEntradaMouseEntered

    private void btnPesquisarEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaMouseEntered
        // TODO add your handling code here:
        this.btnPesquisarEntrada.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnPesquisarEntradaMouseEntered

    private void btnNovaEntradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaEntradaMousePressed
        // TODO add your handling code here:
        this.btnNovaEntrada.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnNovaEntradaMousePressed

    private void btnNovaEntradaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaEntradaMouseReleased
        // TODO add your handling code here:
        this.btnNovaEntrada.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnNovaEntradaMouseReleased

    private void btnEditarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEntradaMouseClicked
          this.btnEditarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         FormEditarEntrada frmEditarEntrada;
        //abrir internal frame
        
        if(EntradaVeiculo.janelaEditarEntrada == false ){
            frmEditarEntrada = new FormEditarEntrada(this.usuario);
            this.Desktop.add(frmEditarEntrada);
            frmEditarEntrada.setVisible(true);
            frmEditarEntrada.toFront();
            frmEditarEntrada.requestFocus();
        }
         this.btnEditarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnEditarEntradaMouseClicked

    private void btnListarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarEntradaMouseClicked
        this.btnListarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FormListarTodasEntradas frmListarEntradas;
        //abrir internal frame        
        if(EntradaVeiculo.janelaListarEntrada == false ){
            frmListarEntradas = new FormListarTodasEntradas(this.usuario);
            this.Desktop.add(frmListarEntradas);
            frmListarEntradas.setVisible(true);
            frmListarEntradas.toFront();
            frmListarEntradas.requestFocus();
        }
        this.btnListarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
    }//GEN-LAST:event_btnListarEntradaMouseClicked

    private void btnEditarEntradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEntradaMousePressed
        // TODO add your handling code here:
        this.btnEditarEntrada.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnEditarEntradaMousePressed

    private void btnListarEntradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarEntradaMousePressed
        // TODO add your handling code here:
        this.btnListarEntrada.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnListarEntradaMousePressed

    private void btnEditarEntradaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarEntradaMouseReleased
        // TODO add your handling code here:
        this.btnEditarEntrada.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnEditarEntradaMouseReleased

    private void btnListarEntradaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarEntradaMouseReleased
        // TODO add your handling code here:
        this.btnListarEntrada.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnListarEntradaMouseReleased

    private void btnPesquisarEntradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaMousePressed
        // TODO add your handling code here:
          this.btnPesquisarEntrada.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnPesquisarEntradaMousePressed

    private void btnPesquisarEntradaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaMouseReleased
        // TODO add your handling code here:
        this.btnPesquisarEntrada.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnPesquisarEntradaMouseReleased

    private void DesktopComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DesktopComponentAdded
        // TODO add your handling code here:
      
    }//GEN-LAST:event_DesktopComponentAdded

    private void btnPesquisarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaMouseClicked
       this.btnPesquisarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FormPesquisaEntrada frmPesquisarEntradas;
        //abrir internal frame        
        if(EntradaVeiculo.janelaPesquisarEntrada == false ){
            frmPesquisarEntradas = new FormPesquisaEntrada(this.usuario);
            this.Desktop.add(frmPesquisarEntradas);
            frmPesquisarEntradas.setVisible(true);
            frmPesquisarEntradas.toFront();
            frmPesquisarEntradas.requestFocus();
        }
         this.btnPesquisarEntrada.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        
    }//GEN-LAST:event_btnPesquisarEntradaMouseClicked

    private void btnNovoFinanciamentoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoFinanciamentoMouseMoved
        // TODO add your handling code here:
        this.btnNovoFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNovoFinanciamentoMouseMoved

    private void btnNovoFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoFinanciamentoMouseClicked
        // TODO add your handling code here:
        this.btnNovoFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        this.lblStatus.setText("Status: abrindo formulário 'Novo Financiamento de Veículo'");
        FormNovoFinanciamento frmNovoFinanciamento;
        //abrir internal frame
        
        if(Financiamento.janelaNovoFinanciamento == false ){
            frmNovoFinanciamento = new FormNovoFinanciamento(this.usuario);
            this.Desktop.add(frmNovoFinanciamento);
            frmNovoFinanciamento.setVisible(true);
            frmNovoFinanciamento.toFront();
            frmNovoFinanciamento.requestFocus();
        }
        this.btnNovoFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        this.lblStatus.setText("Status: Pronto!");
    }//GEN-LAST:event_btnNovoFinanciamentoMouseClicked

    private void btnNovoFinanciamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoFinanciamentoMouseEntered
        // TODO add your handling code here:
        this.btnNovoFinanciamento.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnNovoFinanciamentoMouseEntered

    private void btnNovoFinanciamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoFinanciamentoMouseExited
        // TODO add your handling code here:
        this.btnNovoFinanciamento.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnNovoFinanciamentoMouseExited

    private void btnNovoFinanciamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoFinanciamentoMousePressed
        // TODO add your handling code here:
         this.btnNovoFinanciamento.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnNovoFinanciamentoMousePressed

    private void btnNovoFinanciamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoFinanciamentoMouseReleased
        // TODO add your handling code here:
           this.btnNovoFinanciamento.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnNovoFinanciamentoMouseReleased

    private void btnEditarFinanciamentoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFinanciamentoMouseMoved
        // TODO add your handling code here:
        this.btnNovoFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEditarFinanciamentoMouseMoved

    private void btnEditarFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFinanciamentoMouseClicked
       this.btnEditarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         FormEditarFinanciamento frmEditarfinanciamento;
        //abrir internal frame
        
        if(Financiamento.janelaEditarFinanciamento == false ){
            frmEditarfinanciamento = new FormEditarFinanciamento(this.usuario);
            this.Desktop.add(frmEditarfinanciamento);
            frmEditarfinanciamento.setVisible(true);
            frmEditarfinanciamento.toFront();
            frmEditarfinanciamento.requestFocus();
        }
        this.btnEditarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnEditarFinanciamentoMouseClicked

    private void btnEditarFinanciamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFinanciamentoMouseEntered
        // TODO add your handling code here:
         this.btnEditarFinanciamento.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnEditarFinanciamentoMouseEntered

    private void btnEditarFinanciamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFinanciamentoMouseExited
        // TODO add your handling code here:
        this.btnEditarFinanciamento.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnEditarFinanciamentoMouseExited

    private void btnEditarFinanciamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFinanciamentoMousePressed
        // TODO add your handling code here:
         this.btnEditarFinanciamento.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnEditarFinanciamentoMousePressed

    private void btnEditarFinanciamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarFinanciamentoMouseReleased
        // TODO add your handling code here:
        this.btnEditarFinanciamento.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnEditarFinanciamentoMouseReleased

    private void btnListarFinanciamentoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFinanciamentoMouseMoved
        // TODO add your handling code here:
         this.btnListarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnListarFinanciamentoMouseMoved

    private void btnListarFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFinanciamentoMouseClicked
        this.btnListarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FormListarTodosFinanciamento frmListarTodosFinanciamento;
        //abrir internal frame        
        if(Financiamento.janelaListaTodosFinanciamento == false ){
            frmListarTodosFinanciamento = new FormListarTodosFinanciamento(this.usuario);
            this.Desktop.add(frmListarTodosFinanciamento);
            frmListarTodosFinanciamento.setVisible(true);
            frmListarTodosFinanciamento.toFront();
            frmListarTodosFinanciamento.requestFocus();            
        }
         this.btnListarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnListarFinanciamentoMouseClicked

    private void btnListarFinanciamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFinanciamentoMouseEntered
        // TODO add your handling code here:
        this.btnListarFinanciamento.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnListarFinanciamentoMouseEntered

    private void btnListarFinanciamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFinanciamentoMouseExited
        // TODO add your handling code here:
        this.btnListarFinanciamento.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnListarFinanciamentoMouseExited

    private void btnListarFinanciamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFinanciamentoMousePressed
        // TODO add your handling code here:
        this.btnListarFinanciamento.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnListarFinanciamentoMousePressed

    private void btnListarFinanciamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarFinanciamentoMouseReleased
        // TODO add your handling code here:
        this.btnListarFinanciamento.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnListarFinanciamentoMouseReleased

    private void btnPesquisarFinanciamentoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoMouseMoved
        // TODO add your handling code here:
        this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPesquisarFinanciamentoMouseMoved

    private void btnPesquisarFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoMouseClicked
        this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         FormPesquisaFinanciamento frmPesquisaFinanciamento;
        //abrir internal frame        
        if(Financiamento.janelaPesquisaFinanciamento == false ){
            frmPesquisaFinanciamento = new FormPesquisaFinanciamento(this.usuario);
            this.Desktop.add(frmPesquisaFinanciamento);
            frmPesquisaFinanciamento.setVisible(true);
            frmPesquisaFinanciamento.toFront();
            frmPesquisaFinanciamento.requestFocus();
        }
        this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPesquisarFinanciamentoMouseClicked

    private void btnPesquisarFinanciamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoMouseEntered
        // TODO add your handling code here:
         this.btnPesquisarFinanciamento.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnPesquisarFinanciamentoMouseEntered

    private void btnPesquisarFinanciamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoMouseExited
        // TODO add your handling code here:
        this.btnPesquisarFinanciamento.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnPesquisarFinanciamentoMouseExited

    private void btnPesquisarFinanciamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoMousePressed
        // TODO add your handling code here:
          this.btnPesquisarFinanciamento.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnPesquisarFinanciamentoMousePressed

    private void btnPesquisarFinanciamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoMouseReleased
        // TODO add your handling code here:
        this.btnPesquisarEntrada.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnPesquisarFinanciamentoMouseReleased

    private void pnlPopupMenuFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlPopupMenuFinanciamentoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlPopupMenuFinanciamentoAncestorAdded

    private void btnNovaSaidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaSaidaMouseMoved
        // TODO add your handling code here:
        this.btnNovaSaida.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNovaSaidaMouseMoved

    private void btnNovaSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaSaidaMouseClicked
        this.btnNovaSaida.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         this.lblStatus.setText("Status: abrindo formulário 'Nova Saída de Veículo'");
        FormNovaSaida frmNovaSaida;
        //abrir internal frame
        
        if(SaidaVeiculo.janelaNovaSaida == false ){
            frmNovaSaida = new FormNovaSaida(this.usuario);
            this.Desktop.add(frmNovaSaida);
            frmNovaSaida.setVisible(true);
            frmNovaSaida.toFront();
            frmNovaSaida.requestFocus();
        }
        this.lblStatus.setText("Status: Pronto!");
        this.btnNovaSaida.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnNovaSaidaMouseClicked

    private void btnNovaSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaSaidaMouseEntered
        // TODO add your handling code here:
        this.btnNovaSaida.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnNovaSaidaMouseEntered

    private void btnNovaSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaSaidaMouseExited
        // TODO add your handling code here:
        this.btnNovaSaida.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnNovaSaidaMouseExited

    private void btnNovaSaidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaSaidaMousePressed
        // TODO add your handling code here:
        this.btnNovaSaida.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnNovaSaidaMousePressed

    private void btnNovaSaidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaSaidaMouseReleased
        // TODO add your handling code here:
         this.btnNovaSaida.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnNovaSaidaMouseReleased

    private void btnListarSaidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarSaidaMouseMoved
        // TODO add your handling code here:
        this.btnNovaSaida.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnListarSaidaMouseMoved

    private void btnListarSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarSaidaMouseClicked
        this.btnListarSaida.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FormListarTodasSaida frmListarSaidas;
        //abrir internal frame        
        if(SaidaVeiculo.janelaListarSaidas == false ){
            frmListarSaidas = new FormListarTodasSaida(this.usuario);
            this.Desktop.add(frmListarSaidas);
            frmListarSaidas.setVisible(true);
            frmListarSaidas.toFront();
            frmListarSaidas.requestFocus();
        }
        this.btnListarSaida.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnListarSaidaMouseClicked

    private void btnListarSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarSaidaMouseEntered
        // TODO add your handling code here:
        this.btnListarSaida.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnListarSaidaMouseEntered

    private void btnListarSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarSaidaMouseExited
        // TODO add your handling code here:
         this.btnListarSaida.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnListarSaidaMouseExited

    private void btnListarSaidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarSaidaMousePressed
        // TODO add your handling code here:
        this.btnListarSaida.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnListarSaidaMousePressed

    private void btnListarSaidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarSaidaMouseReleased
        // TODO add your handling code here:
        this.btnListarSaida.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnListarSaidaMouseReleased

    private void btnPesquisarSaidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarSaidaMouseMoved
        // TODO add your handling code here:
        this.btnListarSaida.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPesquisarSaidaMouseMoved

    private void btnPesquisarSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarSaidaMouseClicked
        this.btnPesquisarSaida.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        FormPesquisaSaida frmPesquisarSaidas;
        //abrir internal frame        
        if(SaidaVeiculo.janelaPesquisarSaida == false ){
            frmPesquisarSaidas = new FormPesquisaSaida(this.usuario);
            this.Desktop.add(frmPesquisarSaidas);
            frmPesquisarSaidas.setVisible(true);
            frmPesquisarSaidas.toFront();
            frmPesquisarSaidas.requestFocus();
        }
        this.btnPesquisarSaida.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnPesquisarSaidaMouseClicked

    private void btnPesquisarSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarSaidaMouseEntered
        // TODO add your handling code here:
        this.btnPesquisarSaida.setBackground(corBotaoSubMenuAtivado);
    }//GEN-LAST:event_btnPesquisarSaidaMouseEntered

    private void btnPesquisarSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarSaidaMouseExited
        // TODO add your handling code here:
        this.btnPesquisarSaida.setBackground(corBotaoSubMenuDesativado);
    }//GEN-LAST:event_btnPesquisarSaidaMouseExited

    private void btnPesquisarSaidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarSaidaMousePressed
        // TODO add your handling code here:
        this.btnPesquisarSaida.setBackground(corBotaoSubMenuPressed);
    }//GEN-LAST:event_btnPesquisarSaidaMousePressed

    private void btnPesquisarSaidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarSaidaMouseReleased
        // TODO add your handling code here:
        this.btnPesquisarSaida.setBackground(corBotaoSubMenuReleased);
    }//GEN-LAST:event_btnPesquisarSaidaMouseReleased

    private void pnlPopupMenuSaidaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlPopupMenuSaidaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlPopupMenuSaidaAncestorAdded

    private void btnPagamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagamentoMouseEntered
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnPagamentoMouseEntered

    /**
    * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel btnEditarEntrada;
    private javax.swing.JLabel btnEditarFinanciamento;
    private javax.swing.JLabel btnEntrada;
    private javax.swing.JLabel btnFinanciamento;
    private javax.swing.JLabel btnListarEntrada;
    private javax.swing.JLabel btnListarFinanciamento;
    private javax.swing.JLabel btnListarSaida;
    private javax.swing.JLabel btnNovaEntrada;
    private javax.swing.JLabel btnNovaSaida;
    private javax.swing.JLabel btnNovoFinanciamento;
    private javax.swing.JLabel btnPagamento;
    private javax.swing.JLabel btnPesquisarEntrada;
    private javax.swing.JLabel btnPesquisarFinanciamento;
    private javax.swing.JLabel btnPesquisarSaida;
    private javax.swing.JLabel btnRelatorio;
    private javax.swing.JLabel btnSaida;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlLateral;
    private javax.swing.JPanel pnlPopupMenuEntrada;
    private javax.swing.JPanel pnlPopupMenuFinanciamento;
    private javax.swing.JPanel pnlPopupMenuSaida;
    private javax.swing.JLabel txtIdentificaUsuario;
    private javax.swing.JLabel txtLogout;
    // End of variables declaration//GEN-END:variables
}
