/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.wesleycoelho.view;


import com.wesleycoelho.controllers.jdbc.conn.EntradaVeiculoDB;
import com.wesleycoelho.controllers.jdbc.conn.EstadoDB;
import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Usuario;
import javax.swing.JOptionPane;
import com.wesleycoelho.controllers.jdbc.conn.MunicipioDB;
import com.wesleycoelho.model.Estado;
import com.wesleycoelho.model.Municipio;
import com.wesleycoelho.model.PrintingEntradaVeiculo;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.List;

/**
 *
 * @author Wesley
 */
public class FormEditarEntrada extends javax.swing.JInternalFrame {
    Usuario usuario = new Usuario();
    EntradaVeiculo entrada;
    /**
     * Creates new form FormNovaEntrada
     */
    public FormEditarEntrada(Usuario user) {
        this.usuario = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSalvarEntrada = new javax.swing.JButton();
        btnImprimirEntrada = new javax.swing.JButton();
        btnExcluirEntrada = new javax.swing.JButton();
        btnLimparFormularioEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPesquisarEntrada = new javax.swing.JButton();
        txtPesquisarEntrada = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtModeloEntrada = new javax.swing.JTextField();
        txtMarcaEntrada = new javax.swing.JTextField();
        txtRenavamEntrada = new javax.swing.JTextField();
        txtChassiEntrada = new javax.swing.JTextField();
        txtPlacaEntrada = new javax.swing.JTextField();
        cbAnoEntrada = new javax.swing.JComboBox<>();
        cbCorEntrada = new javax.swing.JComboBox<>();
        cbCidadeEntrada = new javax.swing.JComboBox<>();
        DataChooserEntrada = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        cbUFEntrada = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtProprietarioEntrada = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTelefoneEntrada = new javax.swing.JFormattedTextField();
        txtWhatsappEntrada = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EDITAR entrada de veículo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-car-16_1.png"))); // NOI18N
        setName("janelaEditarEntrada"); // NOI18N
        setVisible(true);
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSalvarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-16.png"))); // NOI18N
        btnSalvarEntrada.setToolTipText("Salvar");
        btnSalvarEntrada.setFocusable(false);
        btnSalvarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvarEntrada);

        btnImprimirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-print-16.png"))); // NOI18N
        btnImprimirEntrada.setToolTipText("Imprimir");
        btnImprimirEntrada.setFocusable(false);
        btnImprimirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirEntrada);

        btnExcluirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-trash-16.png"))); // NOI18N
        btnExcluirEntrada.setToolTipText("Excluir");
        btnExcluirEntrada.setEnabled(false);
        btnExcluirEntrada.setFocusable(false);
        btnExcluirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirEntrada);

        btnLimparFormularioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-broom-16.png"))); // NOI18N
        btnLimparFormularioEntrada.setToolTipText("Limpar Formulário");
        btnLimparFormularioEntrada.setEnabled(false);
        btnLimparFormularioEntrada.setFocusable(false);
        btnLimparFormularioEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFormularioEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFormularioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparFormularioEntradaMouseClicked(evt);
            }
        });
        btnLimparFormularioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormularioEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimparFormularioEntrada);
        jToolBar1.add(jSeparator1);

        btnPesquisarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-16.png"))); // NOI18N
        btnPesquisarEntrada.setMnemonic('P');
        btnPesquisarEntrada.setText("Placa");
        btnPesquisarEntrada.setFocusable(false);
        btnPesquisarEntrada.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnPesquisarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPesquisarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPesquisarEntrada);

        txtPesquisarEntrada.setMaximumSize(new java.awt.Dimension(200, 20));
        txtPesquisarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarEntradaMouseClicked(evt);
            }
        });
        txtPesquisarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarEntradaActionPerformed(evt);
            }
        });
        txtPesquisarEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarEntradaKeyReleased(evt);
            }
        });
        jToolBar1.add(txtPesquisarEntrada);

        jPanel5.setBackground(new java.awt.Color(243, 245, 251));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Veículo"));

        jLabel4.setText("MARCA:");

        jLabel5.setText("MODELO:");

        jLabel6.setText("RENAVAM:");

        jLabel7.setText("CHASSI:");

        jLabel8.setText("PLACA:");

        jLabel9.setText("ANO:");

        jLabel10.setText("DATA:");

        jLabel11.setText("COR:");

        jLabel12.setText("CIDADE:");

        txtModeloEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModeloEntradaKeyReleased(evt);
            }
        });

        txtMarcaEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarcaEntradaKeyReleased(evt);
            }
        });

        txtRenavamEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRenavamEntradaKeyReleased(evt);
            }
        });

        txtChassiEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChassiEntradaKeyReleased(evt);
            }
        });

        txtPlacaEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaEntradaKeyReleased(evt);
            }
        });

        cbAnoEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbAnoEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbCorEntrada.setEditable(true);
        cbCorEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDE", "AMARELO", "PRETO", "CINZA", "AZUL", "BRANCO", "CHUMBO", "PRATA", "VINHO", "BEGE", "VERMELHO", "" }));
        cbCorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyTyped(evt);
            }
        });

        cbCidadeEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ribeirao Preto" }));
        cbCidadeEntrada.setAutoscrolls(true);
        cbCidadeEntrada.setDoubleBuffered(true);
        cbCidadeEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCidadeEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        DataChooserEntrada.setDateFormatString("dd'-'MM'-'yyyy");
        DataChooserEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DataChooserEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel16.setText("UF:");

        cbUFEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo" }));
        cbUFEntrada.setAutoscrolls(true);
        cbUFEntrada.setDoubleBuffered(true);
        cbUFEntrada.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbUFEntradaComponentAdded(evt);
            }
        });
        cbUFEntrada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFEntradaItemStateChanged(evt);
            }
        });
        cbUFEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbUFEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChassiEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenavamEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModeloEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarcaEntrada))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbCidadeEntrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(DataChooserEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbUFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMarcaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRenavamEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChassiEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlacaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(cbAnoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(DataChooserEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbCidadeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbUFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jPanel6.setBackground(new java.awt.Color(243, 245, 251));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        jLabel13.setText("PROPRIETÁRIO:");

        txtProprietarioEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProprietarioEntradaKeyReleased(evt);
            }
        });

        jLabel14.setText("TELEFONE:");

        jLabel15.setText("WHATSAPP:");

        try {
            txtTelefoneEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtWhatsappEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtTelefoneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtWhatsappEntrada))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtProprietarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtProprietarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtWhatsappEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtTelefoneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEntradaActionPerformed
        if(this.entrada == null){ 
             JOptionPane.showMessageDialog(this, "Nenhum registro selecionado!", "Erro", JOptionPane.ERROR_MESSAGE);
             return;
        }        
        String nomeMunicipio;
        String nome_Uf;
        int id_Uf;
        int id_Municipio;
        this.entrada.setNome_proprietario(this.txtProprietarioEntrada.getText());
        this.entrada.setTelefone(this.txtTelefoneEntrada.getText());
        this.entrada.setWhatsapp(this.txtWhatsappEntrada.getText());
        java.sql.Date dataNoFormatoSql = new java.sql.Date(this.DataChooserEntrada.getDate().getTime());
        this.entrada.setData_entrada(dataNoFormatoSql);
        this.entrada.setMarca(this.txtMarcaEntrada.getText());
        this.entrada.setModelo(this.txtModeloEntrada.getText());
        this.entrada.setRenavam(this.txtRenavamEntrada.getText());
        this.entrada.setChassi(this.txtChassiEntrada.getText());
        this.entrada.setPlaca(this.txtPlacaEntrada.getText());
        this.entrada.setCor(this.cbCorEntrada.getSelectedItem().toString());
        nomeMunicipio = this.cbCidadeEntrada.getSelectedItem().toString();
        nome_Uf = this.cbUFEntrada.getSelectedItem().toString();
        id_Uf = EstadoDB.searchIdStateByName(nome_Uf);           
        id_Municipio = MunicipioDB.searchIdByCidade(nomeMunicipio, id_Uf);
        this.entrada.setId_municipio(id_Municipio);
         if(id_Uf == 0 || id_Municipio == 0)
            JOptionPane.showMessageDialog(this, "Erro ao acessar Banco de Dados");
        this.entrada.setAno(this.cbAnoEntrada.getSelectedItem().toString());
        this.entrada.setUsuario(this.usuario.getUsuario());
        EntradaVeiculoDB.Editar(this.entrada);
        JOptionPane.showMessageDialog(this, "Alteração realizada com sucesso!");
    }//GEN-LAST:event_btnSalvarEntradaActionPerformed

    private void btnImprimirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEntradaActionPerformed
       
        try{ 
            if(entrada == null) throw new NullPointerException("Nenhuma entrada localizada!");
            PrinterJob job = PrinterJob.getPrinterJob();
                        job.setPrintable(new PrintingEntradaVeiculo(this.entrada));
                        boolean doPrint = job.printDialog();
                            if (doPrint) job.print();
        }catch(PrinterException  | NullPointerException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimirEntradaActionPerformed

    private void btnExcluirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEntradaActionPerformed

    private void btnLimparFormularioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparFormularioEntradaActionPerformed

    private void txtPesquisarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarEntradaActionPerformed
        // TODO add your handling code here:
        this.txtPesquisarEntrada.setText("");
    }//GEN-LAST:event_txtPesquisarEntradaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        EntradaVeiculo.janelaEditarEntrada = true;
        System.out.println(EntradaVeiculo.janelaEditarEntrada);
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbAnoEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbAnoEntradaAncestorAdded
        // TODO add your handling code here:
        for (int i = 1950; i < 2061; i++) {            
            this.cbAnoEntrada.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_cbAnoEntradaAncestorAdded

    private void txtPesquisarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarEntradaMouseClicked
        //recuperando os dados do formulario
        
        
        
        
    }//GEN-LAST:event_txtPesquisarEntradaMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        EntradaVeiculo.janelaEditarEntrada = false;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        EntradaVeiculo.janelaEditarEntrada = true;
    
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
        EntradaVeiculo.janelaEditarEntrada = false;
   
    }//GEN-LAST:event_formAncestorRemoved

    private void cbCidadeEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCidadeEntradaAncestorAdded
        // TODO add your handling code here:
        List<Municipio> municipios;
        
        municipios = MunicipioDB.selectAllByState("São Paulo");
        for(Municipio municipio: municipios){
            this.cbCidadeEntrada.addItem(municipio.getNome());
        }
     
    }//GEN-LAST:event_cbCidadeEntradaAncestorAdded

    private void cbUFEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbUFEntradaAncestorAdded
        // TODO add your handling code here:
        List<Estado> estados;
        
        estados = EstadoDB.selectAll();
        
      for(Estado estado: estados){
           this.cbUFEntrada.addItem(estado.getNome());
      }
    }//GEN-LAST:event_cbUFEntradaAncestorAdded

    private void cbCorEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbCorEntradaKeyTyped

    private void btnLimparFormularioEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaMouseClicked
        // TODO add your handling code here:
        this.txtChassiEntrada.setText("");
        this.txtMarcaEntrada.setText("");
        this.txtModeloEntrada.setText("");
        this.txtPlacaEntrada.setText("");
        this.txtRenavamEntrada.setText("");
        this.txtProprietarioEntrada.setText("");
        this.txtTelefoneEntrada.setText("");
        this.txtWhatsappEntrada.setText("");
        
    }//GEN-LAST:event_btnLimparFormularioEntradaMouseClicked

    private void DataChooserEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DataChooserEntradaAncestorAdded
        // TODO add your handling code here:
        java.util.Date data = new java.util.Date();
        this.DataChooserEntrada.setDate(data);
                
   
    }//GEN-LAST:event_DataChooserEntradaAncestorAdded

    private void cbUFEntradaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFEntradaItemStateChanged
        // TODO add your handling code here:
        List<Municipio> municipios;        
        municipios = MunicipioDB.selectAllByState(cbUFEntrada.getSelectedItem().toString());
        this.cbCidadeEntrada.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeEntrada.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFEntradaItemStateChanged

    private void cbUFEntradaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbUFEntradaComponentAdded
        // TODO add your handling code here:
        List<Municipio> municipios;        
        municipios = MunicipioDB.selectAllByState(cbUFEntrada.getSelectedItem().toString());
        this.cbCidadeEntrada.removeAllItems();
        for(Municipio municipio: municipios){
            this.cbCidadeEntrada.addItem(municipio.getNome());
        }
    }//GEN-LAST:event_cbUFEntradaComponentAdded

    private void btnPesquisarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarEntradaActionPerformed
        // TODO add your handling code here:
        if( !this.txtPesquisarEntrada.getText().isEmpty()){
            this.entrada = EntradaVeiculoDB.searchByPlaca(txtPesquisarEntrada.getText());
            if(entrada == null){
                JOptionPane.showMessageDialog(this, "Placa não encontrada");
                return;
            }else{              
                this.txtMarcaEntrada.setText(entrada.getMarca());
                this.txtModeloEntrada.setText(entrada.getModelo());
                this.txtRenavamEntrada.setText(entrada.getRenavam());
                this.txtChassiEntrada.setText(entrada.getChassi());
                this.txtPlacaEntrada.setText(entrada.getPlaca());
                this.cbAnoEntrada.setSelectedItem(entrada.getAno());
                this.cbCorEntrada.setSelectedItem(entrada.getCor());
                this.DataChooserEntrada.setDate(entrada.getData_entrada());                  
                this.txtProprietarioEntrada.setText(entrada.getNome_proprietario());
                this.txtTelefoneEntrada.setText(entrada.getTelefone()); 
                this.txtWhatsappEntrada.setText(entrada.getWhatsapp()); 
                
                Municipio municipio;                
                municipio = MunicipioDB.searchById(entrada.getId_municipio());
                
                if(municipio != null){
                    this.cbCidadeEntrada.setSelectedItem(municipio.getNome());
                    Estado estado;
                    estado = EstadoDB.searchById(municipio.getId_uf());
                    if( estado != null){
                        this.cbUFEntrada.setSelectedItem(estado.getNome());
                    }else{
                        JOptionPane.showMessageDialog(this, "Estado não encontrado");
                    }
                }
            }
        }
        
        
    }//GEN-LAST:event_btnPesquisarEntradaActionPerformed

    private void txtMarcaEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaEntradaKeyReleased
        // TODO add your handling code here:
        this.txtMarcaEntrada.setText(this.txtMarcaEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtMarcaEntradaKeyReleased

    private void txtModeloEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloEntradaKeyReleased
        // TODO add your handling code here:
        this.txtModeloEntrada.setText(this.txtModeloEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtModeloEntradaKeyReleased

    private void txtRenavamEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRenavamEntradaKeyReleased
        // TODO add your handling code here:
        this.txtRenavamEntrada.setText(this.txtRenavamEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtRenavamEntradaKeyReleased

    private void txtChassiEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChassiEntradaKeyReleased
        // TODO add your handling code here:
        this.txtChassiEntrada.setText(this.txtChassiEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtChassiEntradaKeyReleased

    private void txtPlacaEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaEntradaKeyReleased
        // TODO add your handling code here:
        this.txtPlacaEntrada.setText(this.txtPlacaEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtPlacaEntradaKeyReleased

    private void cbCorEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyReleased
        // TODO add your handling code here:
        this.cbCorEntrada.setSelectedItem(this.cbCorEntrada.getSelectedItem().toString().toUpperCase());
    }//GEN-LAST:event_cbCorEntradaKeyReleased

    private void txtProprietarioEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProprietarioEntradaKeyReleased
        // TODO add your handling code here:
        this.txtProprietarioEntrada.setText(this.txtProprietarioEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtProprietarioEntradaKeyReleased

    private void txtPesquisarEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarEntradaKeyReleased
        // TODO add your handling code here:
        this.txtPesquisarEntrada.setText(this.txtPesquisarEntrada.getText().toUpperCase());
    }//GEN-LAST:event_txtPesquisarEntradaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DataChooserEntrada;
    private javax.swing.JButton btnExcluirEntrada;
    private javax.swing.JButton btnImprimirEntrada;
    private javax.swing.JButton btnLimparFormularioEntrada;
    private javax.swing.JButton btnPesquisarEntrada;
    private javax.swing.JButton btnSalvarEntrada;
    private javax.swing.JComboBox<String> cbAnoEntrada;
    private javax.swing.JComboBox<String> cbCidadeEntrada;
    private javax.swing.JComboBox<String> cbCorEntrada;
    private javax.swing.JComboBox<String> cbUFEntrada;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtChassiEntrada;
    private javax.swing.JTextField txtMarcaEntrada;
    private javax.swing.JTextField txtModeloEntrada;
    private javax.swing.JTextField txtPesquisarEntrada;
    private javax.swing.JTextField txtPlacaEntrada;
    private javax.swing.JTextField txtProprietarioEntrada;
    private javax.swing.JTextField txtRenavamEntrada;
    private javax.swing.JFormattedTextField txtTelefoneEntrada;
    private javax.swing.JFormattedTextField txtWhatsappEntrada;
    // End of variables declaration//GEN-END:variables
}
