/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.wesleycoelho.view;

import com.wesleycoelho.controllers.jdbc.conn.ClienteDB;
import com.wesleycoelho.controllers.jdbc.conn.EntradaVeiculoDB;
import com.wesleycoelho.controllers.jdbc.conn.FinanciamentoDB;
import com.wesleycoelho.controllers.jdbc.conn.ParcelamentoDB;
import com.wesleycoelho.controllers.jdbc.conn.SaidaVeiculoDB;
import com.wesleycoelho.model.Cliente;
import com.wesleycoelho.model.EntradaVeiculo;
import com.wesleycoelho.model.Financiamento;
import com.wesleycoelho.model.PagamentoTableModel;
import com.wesleycoelho.model.Parcelamento;
import com.wesleycoelho.model.Usuario;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Wesley
 */
public class FormPagamento extends javax.swing.JInternalFrame {
     
      Usuario user;
      List<Cliente> clientes;
      List<Cliente> clientesComFinanciamento = new ArrayList<>();
    /**
     * Creates new form FormPagamento
     */
    public FormPagamento(Usuario usuario) {
        this.user = usuario;
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSalvarEntrada = new javax.swing.JButton();
        btnImprimirEntrada = new javax.swing.JButton();
        btnExcluirEntrada = new javax.swing.JButton();
        btnLimparFormularioEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPesquisarFinanciamento = new javax.swing.JButton();
        txtPesquisarFinanciamento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbFiltroPesquisa = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClientesFinanciamento = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtModeloEntrada = new javax.swing.JTextField();
        txtMarcaEntrada = new javax.swing.JTextField();
        cbAnoCarro = new javax.swing.JComboBox<>();
        cbCorEntrada = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFinanciamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRgFinanciamento = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        txtWhatsappFinanciamento = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTelefoneFinanciamento = new javax.swing.JFormattedTextField();
        txtCPFFinanciamento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtValParcelaFinanciamento = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        cbQtdParcelasFinanciamento = new javax.swing.JComboBox<>();
        txtValEntradafinanciamento = new javax.swing.JFormattedTextField();
        cbDiaVencimentoFinanciamento = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtValVeiculoFinanciamento = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtObsFinanciamento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNFicha = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbParcelasFinanciamento = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("PAGAMENTO");
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                formAncestorRemoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSalvarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-16.png"))); // NOI18N
        btnSalvarEntrada.setToolTipText("Salvar");
        btnSalvarEntrada.setFocusable(false);
        btnSalvarEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvarEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvarEntrada);

        btnImprimirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-print-16.png"))); // NOI18N
        btnImprimirEntrada.setToolTipText("Imprimir");
        btnImprimirEntrada.setFocusable(false);
        btnImprimirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimirEntrada);

        btnExcluirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-trash-16.png"))); // NOI18N
        btnExcluirEntrada.setToolTipText("Excluir");
        btnExcluirEntrada.setEnabled(false);
        btnExcluirEntrada.setFocusable(false);
        btnExcluirEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluirEntrada);

        btnLimparFormularioEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-broom-16.png"))); // NOI18N
        btnLimparFormularioEntrada.setToolTipText("Limpar Formulário");
        btnLimparFormularioEntrada.setEnabled(false);
        btnLimparFormularioEntrada.setFocusable(false);
        btnLimparFormularioEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparFormularioEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparFormularioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparFormularioEntradaMouseClicked(evt);
            }
        });
        btnLimparFormularioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFormularioEntradaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimparFormularioEntrada);
        jToolBar1.add(jSeparator1);

        btnPesquisarFinanciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-16.png"))); // NOI18N
        btnPesquisarFinanciamento.setFocusable(false);
        btnPesquisarFinanciamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarFinanciamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFinanciamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPesquisarFinanciamento);

        txtPesquisarFinanciamento.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisarFinanciamento.setMaximumSize(new java.awt.Dimension(300, 22));
        txtPesquisarFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisarFinanciamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPesquisarFinanciamentoMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPesquisarFinanciamentoMouseReleased(evt);
            }
        });
        txtPesquisarFinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarFinanciamentoActionPerformed(evt);
            }
        });
        txtPesquisarFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarFinanciamentoKeyReleased(evt);
            }
        });
        jToolBar1.add(txtPesquisarFinanciamento);

        jLabel17.setText("     ");
        jToolBar1.add(jLabel17);

        cbFiltroPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOME", "PLACA", "CPF", " " }));
        cbFiltroPesquisa.setMaximumSize(new java.awt.Dimension(300, 22));
        cbFiltroPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbFiltroPesquisaFocusGained(evt);
            }
        });
        cbFiltroPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroPesquisaActionPerformed(evt);
            }
        });
        jToolBar1.add(cbFiltroPesquisa);
        jToolBar1.add(jSeparator2);

        tbClientesFinanciamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "FICHA", "NOME", "CPF", "PLACA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClientesFinanciamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbClientesFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesFinanciamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClientesFinanciamento);

        jPanel5.setBackground(new java.awt.Color(243, 245, 251));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Veículo"));

        jLabel4.setText("MARCA:");

        jLabel5.setText("MODELO:");

        jLabel9.setText("ANO:");

        jLabel11.setText("COR:");

        txtModeloEntrada.setEnabled(false);
        txtModeloEntrada.setMaximumSize(new java.awt.Dimension(400, 2147483647));

        txtMarcaEntrada.setEnabled(false);
        txtMarcaEntrada.setMaximumSize(new java.awt.Dimension(400, 2147483647));

        cbAnoCarro.setEditable(true);
        cbAnoCarro.setEnabled(false);
        cbAnoCarro.setMaximumSize(new java.awt.Dimension(200, 32767));
        cbAnoCarro.setPreferredSize(new java.awt.Dimension(200, 22));
        cbAnoCarro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbAnoCarroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                cbAnoCarroAncestorRemoved(evt);
            }
        });

        cbCorEntrada.setEditable(true);
        cbCorEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VERDE", "AMARELO", "PRETO", "CINZA", "AZUL", "BRANCO", "CHUMBO", "PRATA", "VINHO", "BEGE", "VERMELHO", " " }));
        cbCorEntrada.setEnabled(false);
        cbCorEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbCorEntradaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtMarcaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMarcaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbCorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(208, 208, 208))
        );

        jPanel6.setBackground(new java.awt.Color(243, 245, 251));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel1.setText("NOME:");

        txtNomeFinanciamento.setActionCommand("null");
        txtNomeFinanciamento.setEnabled(false);
        txtNomeFinanciamento.setVerifyInputWhenFocusTarget(false);
        txtNomeFinanciamento.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNomeFinanciamentoCaretUpdate(evt);
            }
        });
        txtNomeFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFinanciamentoFocusGained(evt);
            }
        });
        txtNomeFinanciamento.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtNomeFinanciamentoComponentMoved(evt);
            }
        });
        txtNomeFinanciamento.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtNomeFinanciamentoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtNomeFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeFinanciamentoKeyTyped(evt);
            }
        });

        jLabel2.setText("RG:");

        jLabel3.setText("CPF:");

        try {
            txtRgFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRgFinanciamento.setEnabled(false);
        txtRgFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRgFinanciamentoKeyPressed(evt);
            }
        });

        jLabel25.setText("Telefone:");

        try {
            txtWhatsappFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtWhatsappFinanciamento.setEnabled(false);
        txtWhatsappFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWhatsappFinanciamentoKeyPressed(evt);
            }
        });

        jLabel26.setText("Whatsapp:");

        try {
            txtTelefoneFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneFinanciamento.setEnabled(false);
        txtTelefoneFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneFinanciamentoKeyPressed(evt);
            }
        });

        txtCPFFinanciamento.setEnabled(false);
        txtCPFFinanciamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFFinanciamentoFocusLost(evt);
            }
        });
        txtCPFFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFFinanciamentoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txtWhatsappFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtNomeFinanciamento)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPFFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(txtWhatsappFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefoneFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtRgFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(243, 245, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Financiamento"));

        jLabel12.setText("VALOR PARCELA:");

        txtValParcelaFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValParcelaFinanciamento.setText("0,00");
        txtValParcelaFinanciamento.setEnabled(false);
        txtValParcelaFinanciamento.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValParcelaFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValParcelaFinanciamentoKeyPressed(evt);
            }
        });

        jLabel13.setText("QTD. PARCELAS:");

        cbQtdParcelasFinanciamento.setEditable(true);
        cbQtdParcelasFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "6", "10", "12", "18", "24", "30", "36", "42", "48", "50", "60", "72", " " }));
        cbQtdParcelasFinanciamento.setEnabled(false);

        txtValEntradafinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValEntradafinanciamento.setText("0,00");
        txtValEntradafinanciamento.setToolTipText("");
        txtValEntradafinanciamento.setEnabled(false);
        txtValEntradafinanciamento.setMaximumSize(new java.awt.Dimension(64, 22));
        txtValEntradafinanciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValEntradafinanciamentoActionPerformed(evt);
            }
        });
        txtValEntradafinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValEntradafinanciamentoKeyPressed(evt);
            }
        });

        cbDiaVencimentoFinanciamento.setEditable(true);
        cbDiaVencimentoFinanciamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20", "25" }));
        cbDiaVencimentoFinanciamento.setEnabled(false);

        jLabel15.setText("DIA DE VENCIMENTO: ");

        txtValVeiculoFinanciamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValVeiculoFinanciamento.setText("0,00");
        txtValVeiculoFinanciamento.setToolTipText("");
        txtValVeiculoFinanciamento.setEnabled(false);
        txtValVeiculoFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValVeiculoFinanciamentoKeyPressed(evt);
            }
        });

        jLabel14.setText("VALOR VEÍCULO:");

        txtObsFinanciamento.setEnabled(false);
        txtObsFinanciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtObsFinanciamentoKeyPressed(evt);
            }
        });

        jLabel24.setText("OBS:");

        jLabel16.setText("VALOR ENTRADA:");

        jLabel18.setText("FICHA:");

        txtNFicha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNFicha.setToolTipText("");
        txtNFicha.setEnabled(false);
        txtNFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNFichaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtObsFinanciamento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtValVeiculoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbDiaVencimentoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtValEntradafinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtValParcelaFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtValEntradafinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtNFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cbQtdParcelasFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValVeiculoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(cbDiaVencimentoFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtObsFinanciamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbParcelasFinanciamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbParcelasFinanciamento.setAlignmentX(0.0F);
        tbParcelasFinanciamento.setAlignmentY(0.0F);
        tbParcelasFinanciamento.setColumnSelectionAllowed(true);
        tbParcelasFinanciamento.setShowGrid(true);
        tbParcelasFinanciamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbParcelasFinanciamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbParcelasFinanciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbParcelasFinanciamentoMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbParcelasFinanciamento);
        tbParcelasFinanciamento.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEntradaActionPerformed
        // TODO add your handling code here:
          this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
          this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 

       

    }//GEN-LAST:event_btnSalvarEntradaActionPerformed

    private void btnImprimirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirEntradaActionPerformed

    private void btnExcluirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEntradaActionPerformed

    private void btnLimparFormularioEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_btnLimparFormularioEntradaMouseClicked

    private void btnLimparFormularioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFormularioEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparFormularioEntradaActionPerformed

    private void btnPesquisarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFinanciamentoActionPerformed
        // TODO add your handling code here:
          this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
       if( !this.txtPesquisarFinanciamento.getText().isBlank()){
           if( "NOME".equals(this.cbFiltroPesquisa.getSelectedItem().toString())  ){
               //PESQUISAR FINANCIAMENTO POR NOME
               this.clientes = ClienteDB.buscaClientePorNome(this.txtPesquisarFinanciamento.getText());
               if( Objects.nonNull(this.clientes) || this.clientes.size() != 0){ 
                    DefaultTableModel tableModel = new DefaultTableModel();
                    tableModel = (DefaultTableModel) this.tbClientesFinanciamento.getModel();
                    tableModel.setNumRows(0);               
                    for(Cliente cliente: this.clientes ){
                        int id_entrada;                        
                        id_entrada = SaidaVeiculoDB.buscaIdEntradaPorIdCliente(cliente.getId()); 
                        if(id_entrada != 0){
                            clientesComFinanciamento.add(cliente);
                            Object[] colunas = new Object[9];
                            colunas[0] = FinanciamentoDB.buscaNficha(cliente.getId());//ficha
                            colunas[1] = cliente.getNome();//nome
                            colunas[2] = cliente.getCpf();//cpf
                            colunas[3] = EntradaVeiculoDB.buscaEntradaPorId(id_entrada).getPlaca();  //placa                                      
                            tableModel.addRow(colunas);
                        }
                        
                    }
                      this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));  
                }else{
                   JOptionPane.showMessageDialog(this, "Nenhum resultado encontrado");
                    this.btnPesquisarFinanciamento.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 
               }
           }
       }

    }//GEN-LAST:event_btnPesquisarFinanciamentoActionPerformed

    private void txtPesquisarFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoMouseClicked
        //recuperando os dados do formulario
        this.txtPesquisarFinanciamento.setText("");

    }//GEN-LAST:event_txtPesquisarFinanciamentoMouseClicked

    private void txtPesquisarFinanciamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarFinanciamentoMouseEntered

    private void txtPesquisarFinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarFinanciamentoActionPerformed

    private void cbFiltroPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFiltroPesquisaFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_cbFiltroPesquisaFocusGained

    private void cbFiltroPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroPesquisaActionPerformed
        // TODO add your handling code here:
       
        if( this.cbFiltroPesquisa.getSelectedItem().toString() == "PLACA"){
            this.txtPesquisarFinanciamento.setText("DIGITE A PLACA");
        }else if( this.cbFiltroPesquisa.getSelectedItem().toString() == "NOME"){
            this.txtPesquisarFinanciamento.setText("DIGITE O NOME");
        }else{
           this.txtPesquisarFinanciamento.setText("DIGITE O CPF (APENAS NÚMEROS)");  
        }
        
        
 
    }//GEN-LAST:event_cbFiltroPesquisaActionPerformed

    private void cbAnoCarroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbAnoCarroAncestorAdded
        // TODO add your handling code here:
        for (int i = 1950; i < 2061; i++) {            
            this.cbAnoCarro.addItem(String.valueOf(i));
        }
        
    
    }//GEN-LAST:event_cbAnoCarroAncestorAdded

    private void cbCorEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCorEntradaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCorEntradaKeyTyped

    private void txtNomeFinanciamentoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoCaretUpdate

    private void txtNomeFinanciamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoFocusGained

    private void txtNomeFinanciamentoComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoComponentMoved

    private void txtNomeFinanciamentoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoCaretPositionChanged

    private void txtNomeFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNomeFinanciamentoKeyPressed

    private void txtNomeFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtNomeFinanciamentoKeyReleased

    private void txtNomeFinanciamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFinanciamentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFinanciamentoKeyTyped

    private void txtRgFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRgFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRgFinanciamentoKeyPressed

    private void txtWhatsappFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWhatsappFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtWhatsappFinanciamentoKeyPressed

    private void txtTelefoneFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelefoneFinanciamentoKeyPressed

    private void txtCPFFinanciamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoFocusLost
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtCPFFinanciamentoFocusLost

    private void txtCPFFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFFinanciamentoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtCPFFinanciamentoKeyPressed

    private void txtValParcelaFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValParcelaFinanciamentoKeyPressed
       
    }//GEN-LAST:event_txtValParcelaFinanciamentoKeyPressed

    private void txtValEntradafinanciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValEntradafinanciamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValEntradafinanciamentoActionPerformed

    private void txtValEntradafinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValEntradafinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtValEntradafinanciamentoKeyPressed

    private void txtValVeiculoFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValVeiculoFinanciamentoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtValVeiculoFinanciamentoKeyPressed

    private void txtObsFinanciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsFinanciamentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtObsFinanciamentoKeyPressed

    private void cbAnoCarroAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbAnoCarroAncestorRemoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbAnoCarroAncestorRemoved

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        Parcelamento.janelaPagamento = true;
        System.out.println(Parcelamento.janelaPagamento);
    }//GEN-LAST:event_formInternalFrameOpened

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
          Parcelamento.janelaPagamento = true;
    }//GEN-LAST:event_formAncestorAdded

    private void formAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorRemoved
        // TODO add your handling code here:
           Parcelamento.janelaPagamento = false;
    }//GEN-LAST:event_formAncestorRemoved

    private void tbClientesFinanciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesFinanciamentoMouseClicked
        // TODO add your handling code here:
        int selectedIndexTableClientes = this.tbClientesFinanciamento.getSelectedRow();
        this.txtNomeFinanciamento.setText(this.clientes.get(selectedIndexTableClientes).getNome());
        this.txtCPFFinanciamento.setText(this.clientes.get(selectedIndexTableClientes).getCpf());
        this.txtRgFinanciamento.setText(this.clientes.get(selectedIndexTableClientes).getRg());
        this.txtWhatsappFinanciamento.setText(this.clientes.get(selectedIndexTableClientes).getWhatsapp());
        this.txtTelefoneFinanciamento.setText(this.clientes.get(selectedIndexTableClientes).getTelefone());
        
        Integer id_cliente = this.clientesComFinanciamento.get(selectedIndexTableClientes).getId();
        
        Integer id_entrada = SaidaVeiculoDB.buscaIdEntradaPorIdCliente(id_cliente);        
       
        Integer id_financiamento = SaidaVeiculoDB.buscaSaidaPorIdEntrada(id_entrada).getId_financiamento();
        
        EntradaVeiculo entrada = EntradaVeiculoDB.buscaEntradaPorId(id_entrada);
        
        Financiamento financiamento = FinanciamentoDB.buscaFinanciamentoPorIdSaida(id_financiamento);
        
        this.txtMarcaEntrada.setText(entrada.getMarca());
        this.txtModeloEntrada.setText(entrada.getModelo());
        this.cbAnoCarro.setSelectedItem(entrada.getAno());
        this.cbCorEntrada.setSelectedItem(entrada.getCor());
        
        this.txtNFicha.setText(String.valueOf(financiamento.getFicha()));
        this.txtValParcelaFinanciamento.setText(String.valueOf(financiamento.getValor_parcela()));
        this.txtValEntradafinanciamento.setText(String.valueOf(financiamento.getValor_pago_entrada()));
        this.txtValVeiculoFinanciamento.setText(String.valueOf(financiamento.getValor_veiculo()));
        this.txtNFicha.setText(String.valueOf(financiamento.getFicha()));
        this.cbQtdParcelasFinanciamento.setSelectedItem(String.valueOf(financiamento.getNum_parcelas()));
        this.cbDiaVencimentoFinanciamento.setSelectedItem(String.valueOf(financiamento.getDia_vencimento()));
        this.txtObsFinanciamento.setText(financiamento.getOberservacao());
        
        List<Parcelamento> parcelas = ParcelamentoDB.buscaParcelasPorIdFinanciamento(financiamento.getId());
        if(!parcelas.isEmpty() ){    
            this.tbParcelasFinanciamento.setModel(new PagamentoTableModel(parcelas, financiamento));
        }
    }//GEN-LAST:event_tbClientesFinanciamentoMouseClicked

    private void txtNFichaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNFichaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNFichaKeyPressed

    private void txtPesquisarFinanciamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPesquisarFinanciamentoMouseReleased

    private void txtPesquisarFinanciamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarFinanciamentoKeyReleased
        // TODO add your handling code here:
        this.txtPesquisarFinanciamento.setText(this.txtPesquisarFinanciamento.getText().toUpperCase());
    }//GEN-LAST:event_txtPesquisarFinanciamentoKeyReleased

    private void tbParcelasFinanciamentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbParcelasFinanciamentoMouseReleased
        // TODO add your handling code here:
            
    }//GEN-LAST:event_tbParcelasFinanciamentoMouseReleased

    private void tbParcelasFinanciamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbParcelasFinanciamentoAncestorAdded
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tbParcelasFinanciamentoAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirEntrada;
    private javax.swing.JButton btnImprimirEntrada;
    private javax.swing.JButton btnLimparFormularioEntrada;
    private javax.swing.JButton btnPesquisarFinanciamento;
    private javax.swing.JButton btnSalvarEntrada;
    private javax.swing.JComboBox<String> cbAnoCarro;
    private javax.swing.JComboBox<String> cbCorEntrada;
    private javax.swing.JComboBox<String> cbDiaVencimentoFinanciamento;
    private javax.swing.JComboBox<String> cbFiltroPesquisa;
    private javax.swing.JComboBox<String> cbQtdParcelasFinanciamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbClientesFinanciamento;
    private javax.swing.JTable tbParcelasFinanciamento;
    private javax.swing.JTextField txtCPFFinanciamento;
    private javax.swing.JTextField txtMarcaEntrada;
    private javax.swing.JTextField txtModeloEntrada;
    private javax.swing.JFormattedTextField txtNFicha;
    private javax.swing.JTextField txtNomeFinanciamento;
    private javax.swing.JTextField txtObsFinanciamento;
    private javax.swing.JTextField txtPesquisarFinanciamento;
    private javax.swing.JFormattedTextField txtRgFinanciamento;
    private javax.swing.JFormattedTextField txtTelefoneFinanciamento;
    private javax.swing.JFormattedTextField txtValEntradafinanciamento;
    private javax.swing.JFormattedTextField txtValParcelaFinanciamento;
    private javax.swing.JFormattedTextField txtValVeiculoFinanciamento;
    private javax.swing.JFormattedTextField txtWhatsappFinanciamento;
    // End of variables declaration//GEN-END:variables
}
